---
title: "Word Parser"
author: "Andrew Liu"
date: "2023-08-08"
output: html_document
---

```{r setup, include=FALSE}
#https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=Tabula_Muris
#https://planetcalc.com/3205/
TabulaMuris <- "B(8) Cell(78) Spleen(3) CL(105):0000236(6)		LMO2(4)	LYN(4)	CD74(7)	POU2F2(8)	FCRL1(6)	EBF1(7)	PAX5(7)	POU2AF1(6)	DOK3(10)	IRF5(8)	IRF8(5)	LY6E(4)	LY6D(11)	WDFY4(5)	SERINC3(2)	PTPN6(5)	MS4A1(7)	CD22(7)	CD83(6)	CD81(2)	SDC4(5)	CTSZ(3)	PTPRJ(1)	CTSS(6)	GGA2(1)	SNX2(2)	VPREB3(5)	SP140(2)	BLNK(5)	CD38(8)	CTSH(4)	CD37(8)	CIITA(7)	SWAP70(1)	CR2(5)	NAPSA(8)	MEF2C(5)	SYK(8)	BCL11A(5)	CHCHD10(9)	LY86(10)	RNASE6(6)	IQSEC1(1)	CYBB(12)	PLAUR(2)	MIF4GD(1)	MYO1E(3)	MYO1C(1)	BANK1(7)	BTK(4)	TCF4(4)	PKIG(2)	CHST3(5)	BLK(7)	NOTCH2(1)	PXK(1)	UNC93B1(3)	TNFRSF13C(6)	TNFRSF13B(2)	HVCN1(7)	CXCR5(4)	CAPG(2)	PIK3C2B(3)	RASGRP3(8)	IFI30(3)	CNN3(4)	CD79B(6)	SERP1(2)	CD79A(6)	SPIB(9)	SNN(4)	FCRLA(7)	HHEX(3)	ALDH2(2)	CD19(7)	BTLA(5)	FILIP1L(5)	RALGPS2(5)	CD55(6)	
T(6)   :0000084(6)		SEMA4A(3)	ACTN1(5)	ATP1B3(2)	THEMIS(6)	KBTBD11(5)	DOK2(8)	CD5(7)	ARL4C(4)	CD4(6)	FXYD5(3)	CD7(9)	CD6(7)	ID2(3)	CD28(10)	KLRD1(8)	SIDT1(7)	CAMK4(7)	CD27(6)	HCST(8)	LCP2(10)	CD247(9)	UTRN(1)	SKAP1(11)	ITK(11)	IL18R1(6)	TECPR1(1)	LAT(8)	LEF1(7)	GTF2I(1)	DGKA(3)	CD3G(9)	CTSW(10)	THY1(11)	CD3E(9)	KLK8(4)	CD3D(9)	PITPNC1(3)	SPN(8)	CCND2(3)	EMB(5)	UBASH3A(7)	CTSD(2)	PRKCH(4)	CD96(9)	BCL11B(7)	SH2D1A(8)	NKG7(10)	LIME1(4)	NSG2(7)	DNAJC15(1)	ZAP70(9)	LCK(11)	CD8A(5)	IL2RB(10)	TCF7(8)	PRKCQ(7)	CD226(6)	TOX(3)	IL7R(5)	ITGB2(11)	SELPLG(7)	TXK(11)	ZDHHC24(2)	PRF1(5)	DAPL1(5)	GATA3(5)	PLCXD2(3)	CST7(7)	SLA2(2)	PPM1H(3)	LFNG(1)	KLRK1(6)	RINL(3)	ALS2CL(1)	ZNRF3(1)	LGALS1(2)	LEPROTL1(1)	CCL5(7)	TRAT1(7)	KCNN4(10)	FYN(3)	ITGB7(7)	TMSB10(2)	
Myeloid(2)   :0000763(2)		ACE(1)	GSR(4)	CD300A(10)	CADM3(4)	PILRA(9)	MPEG1(12)	NAV1(2)	LILRB3(12)	TYROBP(13)	MMP9(5)	LILRB4(13)	IL1B(7)	CLEC4D(6)	CLEC4E(5)	CD300E(4)	TGFBI(2)	S100A4(7)	ADAM8(5)	TLR5(1)	CSF3R(7)	IGSF6(9)	GDA(4)	MEFV(2)	IFITM1(6)	PTPRO(9)	HFE(1)	FPR2(5)	FPR1(4)	ATP1A3(6)	TNFAIP2(2)	TIFAB(6)	CLEC7A(14)	CD300LB(4)	NLRP3(5)	CD300LD(11)	SLAMF8(4)	EMILIN2(6)	FCER1G(14)	HAVCR2(2)	BATF3(4)	TCF7L2(1)	GPR35(5)	SLC11A1(10)	ALOX5AP(12)	TBC1D9(3)	FGR(6)	GPR141(6)	DHRS9(3)	TREML4(4)	APOBR(1)	TBC1D8(2)	APOC2(6)	LST1(10)	DOCK5(2)	C5AR1(9)	ADAM23(5)	PYGL(5)	ZBTB46(1)	PRR5L(1)	CSF2RA(10)	CSF2RB(5)	PRAM1(4)	ANPEP(2)	SIRPA(1)	ITGAX(7)	
Basal(4)  Mammary(5) :0000646(1)		TMEM88B(2)	LMO1(2)	DUSP6(2)	KRT5(4)	LAMB3(5)	TPM2(4)		KRT14(2)	RUNX1(4)	DUSP7(2)	PTPRE(1)	MYL6(1)	ACTA2(1)		CRISPLD2(8)	KRT17(1)	RBP1(5)	SLPI(3)	KRT15(3)	COL9A2(1)	ID4(2)	COL9A3(1)	MYL9(3)	EMID1(3)	CHI3L1(4)	CDA(2)	TES(1)	COL16A1(3)	FBLIM1(1)	TAGLN(3)	CPNE8(1)	LMOD1(5)	CXCL14(3)	PLTP(6)	PDLIM4(2)	PDLIM3(4)	CDH3(3)	WIF1(1)	CSRP1(1)	PERP(3)	TPM1(2)	FLNA(1)		COTL1(2)	PHLDA3(1)	ATXN1(1)	MYH11(4)	JAG1(1)	WNT10A(4)	GSTO1(3)	RBPMS(1)	IGFBP3(4)	FST(4)	DSTN(2)	SORBS1(1)	FERMT1(2)	ARC(1)	GJB3(2)	BCAM(7)	PALLD(2)	GJB4(1)	SMTN(2)	STAC2(1)	NCL(2)		SNAI2(2)	LGR5(2)	LGR4(2)	IL17B(1)	MOXD1(2)	COL17A1(3)	LAMA3(5)	LUZP1(1)	TMEM51(3)	SRM(1)	PLA2G7(10)	LTBP2(1)	ICAM1(1)	MYLK(4)	ACTG2(1)	SOX4(4)	CHADL(1)	CNN1(1)	TUBA1C(1)	GJA1(4)	CALD1(2)	TRIM29(2)	PMEPA1(3)	MICAL2(1)	APOE(4)	SFN(4)	SYNPO(1)	LGALS7(2)	
Endothelial(10)   :0000115(9)			UNC45B(7)	BTNL9(6)	EGFL7(13)	SRGN(4)	TCF15(8)	SH2D3C(3)	PPP1R16B(7)	RSAD2(3)	ARAP3(4)	PARVB(3)	BMX(4)	RBP7(6)	EMCN(11)	ABI3(2)	MMRN2(12)	PTPRB(11)	TAL1(2)	BCL6B(3)	PECAM1(12)	SHANK3(3)	CLIC5(6)	PLVAP(5)	RGS16(1)	USHBP1(11)	RASGRF2(4)	AQP7(4)	GIMAP4(10)	ADCY4(6)	GIMAP5(6)	GIMAP6(10)	IL2RG(7)	RASIP1(10)	SHE(2)	DLL4(4)	APOLD1(7)	LRRC32(4)	ECSCR(8)	PREX2(4)	CDH5(13)	MYCT1(10)	DENND3(2)	KDR(9)	S1PR1(10)	JAM2(6)	TNFAIP8L1(3)	CD36(5)	LMCD1(2)	CD300LG(9)	GBP4(4)	SEMA6B(1)	NOS3(8)	CD93(11)	ARHGEF15(9)	TIE1(11)	GPR4(8)	IGF2(3)	FABP4(8)	NOVA2(1)	ERG(6)	ESAM(10)	ENG(10)	GPR146(1)	NRP1(6)	ROBO4(9)	FLT1(11)	FLT4(8)	HDC(4)	SEMA3G(1)		GATA2(7)	ICAM2(11)	PCDH17(4)	ENDOU(3)	THBD(5)	EDNRB(6)	SOX18(10)	C1QTNF9(6)	SOX17(9)	STMN2(3)	CYYR1(6)	SCARF1(2)	SEMA7A(5)	GPIHBP1(9)	
Luminal(1) Epithelial(5)   Gland(1)  :0002326(1)		PTPN18(5)	CMTM8(3)	PRLR(3)	BIK(1)	CORO2A(4)	GALNT3(3)	CGN(4)	KRT8(3)	KRT7(6)	BSPRY(2)	TMPRSS13(4)	ATP1B1(8)	TMC4(2)	GRHL1(2)	MMP15(1)	ELF3(4)	CEACAM1(4)	KRT19(6)	SPINT2(5)	KRT18(5)	ELF5(1)	SPINT1(4)	SCNN1B(4)	SPNS2(2)		PKP2(2)	RHOV(4)	MANSC1(1)	ALDOC(2)		CLIC6(1)	EHF(4)	CD82(3)	TMPRSS2(5)	CLU(4)	AQP5(6)	CSN3(1)	CLDN3(4)	MUC1(3)	RAB11FIP1(3)	EPCAM(4)	MARVELD3(3)	BASP1(7)	CCND1(3)	MARVELD2(1)	RAB25(6)	RHPN2(1)	MYH14(5)	PRSS8(3)	MAL2(4)	VILL(1)	MPZL3(1)	TMEM30B(1)	ARRDC1(1)	ST14(3)	TNK2(1)		WNT7B(3)	DKKL1(1)	INHBB(1)	SULF2(3)	LRG1(4)	SLC9A3R1(2)	MBOAT1(1)	MED24(1)	CLDN7(5)	OCLN(5)	MLPH(2)	CLDN4(5)	KIT(4)	ALDH1A3(2)	GDPD1(1)	TOM1L1(1)	SMAGP(3)	MUC20(2)	LTF(2)	ATP6V1B1(3)	TJP3(1)	NOTCH3(8)	CRB3(3)	TACSTD2(5)	FCGBP(3)	PLB1(1)	LGALS3(7)	LIPH(1)	MUC15(1)		CD14(6)	
Stromal(3)   :0000499(3)		PDGFRA(8)	LUM(5)	SCARA5(3)	MMP3(1)	RARRES2(8)		EBF2(4)	FN1(5)	LRRC61(3)	BICC1(3)	COL1A2(8)	FXYD1(7)	TMEFF2(3)	MFAP5(5)	COL1A1(7)	CCDC80(5)	COL3A1(7)	ZEB2(1)	COL5A2(7)	OGN(6)	COL5A1(7)	FAP(4)	MMP19(1)	COL5A3(4)	FNDC1(4)	DPEP1(6)	MXRA8(5)	CD248(7)	DDR2(9)	ITIH5(2)	ENPEP(3)	NNMT(2)	NID1(5)	TNXB(6)	FGL2(3)	TNFAIP6(3)	METRNL(4)		LOXL1(7)	LOXL2(5)	CLEC3B(6)	SRPX2(4)	PENK(2)	CTSK(5)	ABI3BP(6)	HAS1(2)	SERPINF1(6)		CPXM1(5)	SLIT3(4)	CD34(6)	IGFBP6(5)	PCOLCE(8)	QPCT(3)	IGF1(4)	SOD3(5)	DCN(7)	COL6A1(8)	NOVA1(1)	LRRN4CL(3)	COL6A3(6)	COL6A2(8)	SERPING1(6)	MNDA(4)	PCOLCE2(4)	PLA1A(2)	SRPX(4)	COLEC12(7)	LSP1(3)	CCL11(4)	LAMA2(6)	DPT(4)	LRRC17(2)	LPL(3)		HTRA3(5)	OLFML2B(4)	THBS3(3)	ISLR(6)	THBS2(4)	LPAR1(5)	CYGB(7)	EFEMP1(2)	ADAMTS5(3)	ADAMTSL1(2)	SGCE(1)	NDN(3)	MRC2(6)	SVEP1(5)	APOD(5)	
  Thymus(2) :		IL16(1)	TSC22D4(1)	RHOH(3)	DNTT(1)		CLK3(1)	DEF6(1)		PTPRC(17)						PTPN7(2)		ARPP21(1)							SATB1(8)	CELF2(1)	SH2D2A(10)	ARHGEF1(1)	SLA(7)	IL21R(5)				LIMD2(4)	JAKMIP1(4)			LDHB(5)	CCND3(1)	MYB(2)	TBXA2R(3)	CCR9(3)		SLC16A5(2)	SASH3(2)	KLF13(2)		EDEM1(1)			DCK(1)			PRRC2C(1)						PTPRCAP(12)	RAMP1(3)				AQP11(1)	SH3KBP1(2)	CDCA7(3)		GMFG(5)	RORC(1)		SMC4(1)	CORO1A(8)	ETS1(7)	ITGAL(10)	HDAC7(1)				ZNRF1(1)		ARL5C(3)	RASGRP1(3)	RMND5A(1)	STMN1(3)	ARHGDIB(5)	MIER1(1)	AP3S1(1)			RAG1(2)	RAG2(1)	
Mesenchymal(4) Stem(7)   :0000134(2)			MREG(3)		FCRL5(2)			SYN2(1)	PAWR(1)		CPD(1)		IL9R(1)		PCDHB9(1)			HSPA1B(1)	SLC46A2(1)	FAM43A(1)	SDC3(3)	LRRK2(1)	ATOH8(1)	FGD5(4)		ITPRIPL2(1)	RASGEF1B(2)	TRIM6(1)	RRAS(1)		DENND5B(3)	HES1(2)								SLC30A1(1)		ELL2(1)	LIMA1(1)		TJP1(1)		MYO1B(2)	RAB13(1)	KCTD14(3)	KCTD12(2)		SEMA3A(3)	PRR5(1)		PLEK(8)	KCNA5(4)	PDGFA(1)	LPO(1)				IL4I1(1)				RUSC2(1)	KYNU(1)		UBD(1)	TNFSF12(1)	SERPINH1(4)	PLCG2(5)	SOX7(7)	PCDH1(1)	
  Pancreas(9) :			ITGA1(3)							MALL(7)			ARHGAP31(2)	ID1(5)			TEK(7)		THRSP(4)	HOXD8(2)	LIMS2(2)	RAMP3(4)		SLFN5(5)						CLEC14A(4)				CYP26B1(2)	TMEM204(4)								FZD4(1)						FLI1(2)	IFI44(3)	ACER2(5)	PLSCR2(2)	FAM167B(4)		KIF26A(1)	HECW2(2)			CALCRL(6)		RTP3(2)	HOXD3(1)	LDB2(2)			DYSF(3)	COL13A1(2)	THSD1(2)					ESM1(3)	CLEC1A(2)			PODXL(9)					EPHB4(1)	
Leukocyte(5)  :0000738(5)		CCR2(8)	LRRC25(10)			IL10RA(7)	NFAM1(7)					VAV1(4)	RUNX3(5)	ARHGAP25(2)	LAT2(1)	APBB1IP(2)			FCGR2B(10)	ARHGAP30(6)		NCF1(4)		DOCK2(4)	CD86(8)	GPSM3(2)	CD84(3)			PTPN22(11)	GPR65(6)	PLD4(11)			SLAMF9(7)	TNFAIP8L2(3)		SLAMF7(10)	LPXN(4)	CD52(13)	SLC15A3(6)			NCKAP1L(6)			HCK(9)	MYO1F(7)	HCLS1(6)	RGS10(2)	CD48(6)	PLCB2(2)	MS4A7(6)	PPP1R18(1)	NCF2(7)	NCF4(5)	WAS(3)	IKZF1(3)	AIF1(9)			ARHGAP15(4)	CYTH4(8)	INPP5D(4)	RGS1(6)	CCL4(4)		CCL3(3)	PMAIP1(2)	AMZ1(3)	
Pancreatic(7) A(2)   :0000171(1)		HHATL(3)	GPX3(6)	EDN3(2)	SMARCA1(2)	KCNIP3(3)	VWDE(1)	ETV1(2)	GCG(1)	SSTR2(1)	A1CF(1)	PYY(3)	POU6F2(2)	NAP1L5(2)	SFRP5(3)	PTPRD(3)	RCN3(6)	MFAP2(3)	RBP4(5)	FEV(4)	SLC25A33(1)	PAPPA2(3)	FBP1(3)	KCNK3(6)	GALNT13(2)	ATF3(1)	KLB(1)	HAPLN1(2)	TMEM59L(3)		GLS(1)	C8B(2)	SLC7A2(1)	IGSF21(2)	DOCK11(1)	CALB1(3)		ADAMTS18(1)	NXPH1(3)	GPR119(2)	GRB10(1)	PAK3(1)	IRX2(3)	IRX1(2)	ARG1(3)	GADD45B(1)	AVPR1B(2)	MAFB(2)	CIT(2)	GFRA3(2)	ACE2(6)		GNAS(3)	CTXN2(2)	MAP3K15(1)	GRIA2(2)	RAB3C(4)	DPP10(1)	GRIA3(2)	MAMLD1(1)	OXTR(1)		ARX(4)	CRYBA2(2)	KLHL13(1)	PPP2R2B(1)	GNAI1(3)	HIGD1A(1)	AARD(2)	TTR(2)	CST3(5)	NUDT11(1)	RGS4(5)	RESP18(3)	NDST4(2)	PDK4(1)	NEFM(5)	GC(3)	UPP1(1)	PCSK1N(3)	CACNG4(3)	FAM81A(3)	BEND7(1)	SLC38A5(1)	
 D(1)   :0000173(1)		CHGB(3)	ZFHX4(1)	RBFOX3(2)	MAGEE2(1)	CACNA2D2(1)	SFTPD(3)	LMO3(1)	SHISA6(1)	CACNA2D3(1)	SSTR1(2)	CIDEA(2)	LINGO1(2)		SEZ6L(3)	BMP3(2)	SST(1)	TOX2(1)	PCP4(1)	BAMBI(2)	CALY(2)		CNTN3(1)	FILIP1(1)	NBL1(6)	LY6H(3)	ACHE(1)		KCNC2(1)	CPNE5(2)	CD164L2(2)	NRXN2(2)		DGKB(3)	EFNA5(1)	EFNB3(2)	DPP6(2)	FRZB(2)	RASGEF1A(2)	DACH2(1)	NNAT(1)	SPOCK3(2)	PPFIA2(1)	SPOCK1(1)	CPNE4(1)	NCAM2(1)	DSCAM(2)	MEST(1)	SCN3B(1)	GHSR(1)	CER1(1)	HGFAC(2)	SYT6(1)	ANKRD34B(1)	KCND2(1)			UNC5C(1)	SYT1(3)	HGF(1)	TMEM132B(1)	STXBP5L(3)	F5(2)	KCTD8(1)	GREM2(1)	PER3(2)	TMIE(1)	GAP43(1)	KLHDC8B(1)	DCT(1)	FGF14(2)	NEUROG3(1)	GPM6A(3)	PARM1(6)	RAB3B(2)	PPP1R17(2)	NTM(2)	PCDH15(2)	FSTL5(1)	CACNA1H(4)	FGF9(1)		PTPRZ1(3)	CREG2(1)	TSPAN8(2)	PPY(2)	RGS9(1)	KCNJ4(2)	
 PP(1)   :0002275(1)		PTPRN2(2)		JUN(2)	NKX6-3(1)		APLP1(2)	ABCC8(3)		SEMA4F(2)	PEG3(3)	OCRL(1)		ZWINT(1)				EEF1A2(2)	ARL4D(3)		MORF4L2(1)	OLFM3(1)					CPE(4)		PAM(2)	SCG5(2)				PCSK2(1)	RTN1(1)	NCAM1(3)		UCP2(2)			ITPR1(1)	PLD3(1)	LRRTM1(1)		BSG(2)	FAM184B(1)	SCN3A(3)	EGR1(2)	JUND(2)	KCNH6(2)	ST8SIA3(1)	FOS(1)	KCNK16(2)	PTOV1(2)	SLC16A10(1)	PGRMC1(1)		DDOST(1)	FOSB(2)	PRKAR1A(1)	NUCB1(1)	P4HB(1)			ITM2B(2)	ITM2C(1)	FOLR1(3)			SPON2(3)	MAGED1(2)		LGALS3BP(1)	TUBA1A(3)	SCGN(2)			TSPAN7(7)		VSIG1(1)		MC4R(1)	SDF4(1)	PIM2(2)				JUNB(2)		
 Acinar(1)   :0002064(1)		GAMT(1)	GALNT6(5)	HOMER2(1)	CACHD1(1)	GP2(1)	CELA1(2)	NUPR1(6)	ERP27(1)	CTRL(1)	COL7A1(1)	PAH(3)	ZG16(1)	TFF2(1)	SERPINI2(1)	CTRC(1)	PTF1A(1)	PNLIPRP2(1)	PRSS2(1)	GLS2(1)	RBPJL(2)	PRSS1(1)	PNLIPRP1(1)	KLK1(4)	LRRC7(1)	SLC1A5(2)	SLC7A11(4)	EXTL1(1)	SPDEF(2)	CASP9(1)	CCKAR(2)	RAB26(1)	FGF21(1)	PRSS3(1)	TEAD2(2)	SLC39A5(1)	CELA2A(1)	EDARADD(2)	CPA2(1)	PDIA2(1)	CPA1(1)	CEL(1)	GNMT(2)	RNASE1(1)	GAL(2)	IL22RA1(2)	NAT8(1)	SLC6A9(1)	NPHS1(1)	GJB2(1)	CLPS(2)	MYO5C(4)	P2RX1(3)	SYCN(1)	CTRB1(1)	CHST2(2)	MATN4(3)	PNLIP(1)	CELA3B(1)	CPB1(1)	PLA2G1B(2)	AMY2B(1)	ARHGEF26(2)	DERL3(1)	HSD17B13(1)	GDPD5(1)	GATA4(1)	ARHGDIG(1)	CABP2(1)	CUZD1(1)	RANBP3L(1)	DMBT1(2)	SOSTDC1(2)	SLC38A3(1)	GGT1(4)	SLC19A2(1)	
 Ductal(1)   :0002079(1)		BCHE(1)	SCARA3(3)	ANGPT1(3)	TNFRSF19(3)	SPHK1(1)	MMD2(2)	TMEM171(1)	CP(2)	CLDN10(4)		GSTA4(5)	GSTA3(3)		SLC28A3(1)	GAS6(1)	SHANK2(1)	COL18A1(2)	SEMA5A(3)	VTCN1(3)	TINAGL1(8)	ONECUT1(1)	SLC5A1(2)	KRT23(5)	HS6ST2(3)		ADAMTS16(1)	CASP12(1)	DPYSL4(1)	SPP1(2)	ST3GAL4(1)	SLC39A4(1)	HABP2(1)	SLC15A2(2)	STAT4(7)	TSTD1(1)	ANXA13(2)	DDIT4L(3)	FMO2(2)	NGF(1)	AIF1L(2)	PTGR1(1)		EVC(1)	GJB1(3)	CAT(2)	NFIB(4)	APOC1(2)	PPP1R1B(1)	KCNQ1(2)	CLDN8(5)	CDC42EP1(2)	CRYAB(2)	FGFR4(3)	PIK3AP1(4)	TMEM229A(2)	FGFR3(2)	CFTR(3)	FGFR2(3)	APCS(2)	CRP(3)	KCNE3(2)	SH2D4A(1)	HPN(1)	PIGR(1)	PDGFC(1)	WFDC2(8)	PRELP(5)	MGST1(6)	OLFML2A(3)	WFDC3(2)	TNS1(1)	TGM2(2)	SULT1A1(2)	FADS3(1)	IGFBPL1(2)	PKHD1(1)			CLMN(1)	ENC1(1)	PALMD(7)	SOX9(4)		EFHD1(3)	FADS2(2)	
 Stellate(1)   :0002410(1)		PDGFRB(5)		AOC3(4)	PRRX1(3)					GPX8(2)	GDF10(4)	DES(4)	BMP4(3)		AXL(6)				ITGA11(3)			CSPG4(7)							ADM(1)	AEBP1(7)	ATP1A2(3)		PEAR1(1)	ADAMTS12(1)	REM1(2)	GPR153(2)	GJC1(2)		FOXS1(3)	SCN7A(5)		CYP1B1(1)		S1PR3(3)	HSD11B1(5)	PPP1R14A(2)	TBX2(4)	IL34(5)	GGT5(3)	PTGIS(5)	G0S2(4)	PODN(5)	ASPN(4)		LOX(1)	HAND2(1)	NDUFA4L2(6)	PLA2R1(2)	SNAI1(1)	VGLL3(1)	ANGPTL2(2)	FBN2(1)		STEAP4(2)	KCNE4(3)		COL15A1(3)	C1S(6)	TCF21(4)	PLAU(1)	HTRA1(4)	GLI2(1)	LRRC55(1)	HIGD1B(5)	LTBP1(5)	ADCYAP1R1(2)		PCDH18(3)	VTN(3)			GLI3(3)		ARHGAP20(2)	C1QTNF7(4)		ADAMTSL3(1)	NAALAD2(1)	RSPO3(2)		MSC(1)	
Type(3)     :0000169(1)		CHGA(1)		VDR(2)	ENTPD3(2)	KCNIP1(3)	INSRR(2)	IL1R1(1)	DENND4C(1)	HS3ST6(3)	G6PC2(1)	GNG12(1)	KY(1)	SYTL4(1)		GJD2(1)	TMEM215(1)	BMP1(1)	IAPP(1)	ITPKB(1)		RNF182(1)	SCG2(2)	CNTFR(1)	CHIC1(1)	CNTNAP2(2)	PCSK1(2)	GALNT14(1)	RASGRF1(2)	IGFALS(1)	MAOB(1)	TMPRSS4(3)	GLP1R(1)	PRUNE2(3)	HEPACAM2(4)	TMEM163(2)	COX6A2(3)	HAPLN4(1)		DEFB1(4)		KLHL32(1)	ENHO(1)	PAPSS2(1)	PRSS53(2)		SH3PXD2A(1)	SPOCK2(2)	EMILIN1(3)	PHACTR1(1)	MUC4(1)	NKX6-1(2)	GPR158(2)	NTRK2(2)	SLC30A8(1)	WFS1(1)	ACOT11(2)	GAD1(2)	PDX1(1)	PRKCA(2)	MAFA(1)	ADRA2A(1)	FKBP1B(1)	BACE2(5)	SDK2(1)	NELL1(1)	FHDC1(1)	PPP1R1A(2)	FAM151A(1)	MLXIPL(1)	PITPNM3(2)	INSM1(4)	PDE5A(2)	SPC25(3)	SLC22A23(1)	VIL1(1)	PFKFB2(1)	SLC24A2(1)	DDC(1)	TTYH2(1)	GPR45(1)	SLC2A2(1)	TMTC3(1)	ATP2A3(4)	ATP2A2(1)	ZDHHC2(2)	SLC4A7(1)	PCLO(1)	UCN3(1)	GALR1(2)	SLITRK6(1)	HADH(1)	TRPM5(2)	
Cardiac(1) Muscle(11)  Heart(7) :0000746(1)		KCNJ5(1)		TRDN(1)	APOBEC2(1)	TRIM63(1)	MYBPC3(1)	KCNJ11(1)		CKM(1)	MYOCD(3)	ACTN2(4)	MTUS2(1)	TECRL(1)	MLF1(3)	TUBA8(1)	OBSCN(2)	MYL1(2)	SYNPO2L(1)	YIPF7(1)	HRC(3)	ITGB1BP2(1)	ALPK2(1)	TRIM54(1)		DSC2(2)	MYH7(2)	CHRM2(1)	HSPB7(2)	HSPB6(2)	CITED4(2)	SMPX(1)	LMOD2(1)	ASB14(1)	FITM1(1)	PPP1R3A(1)	KLHL31(1)	LRRC2(2)	SYNGR1(2)	CSRP3(2)	ASB11(1)	DHRS7C(1)	MOV10L1(1)	NRAP(1)	XIRP2(1)	ANKRD1(2)	FSD2(1)	XIRP1(2)	SMYD1(2)	BVES(1)	DSP(2)	PPP1R14C(3)	CPT1B(1)	TNNC1(1)	PGAM2(2)	TNNI3K(1)	ADPRHL1(1)	ANK1(1)	RPL3L(1)	FRMD5(1)	SBK2(1)	TXLNB(1)	PLIN5(1)	TCAP(2)	RYR2(1)	MYOM1(3)	MYOM2(1)	MYLK3(1)	SLC47A1(1)	POPDC2(2)	FHOD3(1)	LDB3(2)	MYPN(1)	SRL(1)	MYLK4(1)	LRRC10(1)	PLN(3)	CKMT2(2)	SGCG(1)	ART1(1)	CMYA5(2)	NPPB(1)	SGCA(3)	MYO18B(1)	SCN5A(1)	NRTN(1)	MYOZ2(1)	KCNJ3(1)	CORIN(1)	
Endocardial(1)   :0002350(1)		ENTPD1(2)		UNC13B(1)	APLP2(1)	KLHL4(2)		PTPN14(2)		TM4SF1(6)								DSG2(3)	IRF6(2)	FOXC2(1)	KANK1(1)		FOXC1(2)	NPR3(1)		DPP4(1)		PROKR2(1)	COMP(1)	HMCN1(3)			CGNL1(2)		AHSG(2)	CISH(1)	IGFBP5(2)		VWF(1)	ZBTB39(1)	COL23A1(2)	NR2F2(3)	RAB27A(2)	ATP2B4(3)		CBFA2T3(4)				TMEM158(1)	FABP5(3)	GPR182(3)	MAL(5)	CDH11(2)	SMOC1(1)	PKHD1L1(2)	PTX4(1)		PRR15(1)			BEX4(2)	SLC45A3(1)	COLEC11(2)	MEGF6(1)	WIPF3(2)	AMIGO2(3)	ECE1(4)		PTGS1(4)	THSD4(1)	TMEM100(2)		SALL1(2)		SNCAIP(1)	FAM174B(1)	STAB1(4)	TMEM108(1)	PLAGL1(1)	RPS6KA2(1)	TSPAN6(2)	SOST(1)	TNFSF10(3)	CYTL1(1)	A2M(2)	PGM5(1)	ENPP6(2)	
   :									CAV2(5)		CAV1(4)						APLNR(3)		ITGA6(6)		SLC28A2(1)	MGLL(5)	SGK1(4)		KANK3(5)								MEOX2(1)	AQP1(6)				SLC9A3R2(8)		ABLIM3(3)	MCF2L(4)		CCDC85A(3)			TIMP4(5)									MYO10(1)	CYP4B1(5)		HSPA12B(2)		CLDN5(6)					F11R(6)		TSPAN13(4)			GNG11(4)			TMEM88(4)					PDE2A(6)			SCARB1(3)		
Erythrocyte(1)  :0000232(1)		UBE2C(4)	TM4SF4(2)	APOA5(1)	APOA4(1)	AZGP1(2)	HAL(1)	CPS1(1)	CTH(1)	RELL2(1)	TRIM10(1)	SLC25A37(1)	SERPINA12(1)	GYPA(1)	PON1(2)	SAA4(1)	LEAP2(1)	AQP8(2)	C8A(1)		OPRL1(1)	UBE2L6(1)	PIPOX(1)	SUSD4(2)	HAO1(1)	ASPDH(1)	SNCA(1)	PLA2G12B(1)	TTC36(3)	AADAT(1)	PKLR(1)	HGD(3)	TNNC2(1)	ELOVL3(1)	GCGR(1)	ACOT12(1)	APOC4(2)	BPGM(1)	BAAT(1)	AADAC(2)	SAA2(2)	AGXT2(1)			ALAS2(1)	CPB2(2)	AFM(1)	ASGR1(1)	SLC4A1(1)	PLG(1)	DDN(1)	CHRDL2(2)	APOM(2)	TNFRSF8(1)	UGT3A2(2)	APOF(1)	
Fibroblast(2)  :0000057(2)		GSN(6)	GSTM5(2)	ENTPD2(4)				MMP2(6)		GFPT2(3)			PDGFRL(1)							MMP14(2)	MGP(4)				MFAP4(2)		GAS1(5)	PMP22(4)			TMEM45A(2)		COL14A1(3)		LRP1(5)	ELN(1)			FBLN1(4)	PCSK6(2)	SFRP1(4)		FBLN5(3)	PDLIM2(4)		PDPN(2)						IGFBP4(2)		BGN(4)				SULF1(1)				ALDH1A1(5)	SMOC2(4)			FGFR1(5)	MATN2(3)	SDC2(4)			ECM1(4)	GPM6B(2)	CEBPD(3)				FHL1(4)			FSTL1(5)			GSTT1(1)						OLFML3(5)	ADAMTS2(6)			ENPP2(2)		
  :			CD163(5)	CD72(6)														LCP1(5)		PF4(4)		CD68(11)						C3AR1(4)				ALOX5(7)							CCR5(4)	CTSC(1)	EPSTI1(5)	MSR1(7)	CD53(8)			TIMD4(4)				LAPTM5(3)	PRKCB(8)		SNX20(3)			TBXAS1(3)		FOLR2(4)	FERMT3(2)	CSF1R(8)						CLEC12A(7)		F13A1(6)		ITGAM(9)		CFP(6)	LILRA5(3)			MRC1(7)	RAC2(10)		
Smooth(3)    :0000192(3)			GUCY1A2(2)	KCNJ8(2)		ABCC9(2)		SLC12A2(3)	KLHL23(1)	ATP1B2(2)		PHOX2A(1)	GPRC5C(4)	RAB37(5)	RDH5(1)	SERPINI1(1)	ITGA7(4)			CPM(5)	RASL12(3)		BCAR3(2)	HRK(1)		NXPH4(2)	COX4I2(4)	RASL11A(3)		NRXN1(1)		AGAP2(1)		ADCY6(1)		NRIP2(3)	PDE4C(2)	SNCG(4)				P2RY14(2)		IQSEC3(1)	MCAM(2)	EPHX3(4)	TRPC3(2)	ARHGEF17(1)			SLC16A12(3)	ADRA2B(1)	SLC4A8(2)	ANO1(7)			DAAM2(1)		IL2RA(1)		CASQ2(3)		RERG(2)					SLC38A11(5)	BHLHE22(1)	LIN7A(1)		RASGRP2(2)			RGS5(3)	EDNRA(4)		GJA4(6)	EGFLAM(3)	KCNMB1(3)	COBLL1(1)	CHN1(2)	RBPMS2(3)	
  Lung(17) :		SEMA4B(3)	GPR18(2)				DUSP2(6)	PYHIN1(3)					RHOF(4)	PDCD1LG2(1)	CD2(13)		BFSP2(1)	SLC9A7(1)			CD69(6)				PGAP1(2)					SLAMF6(4)	CCR7(8)	CCR6(3)	SRPK3(2)			SLC38A1(3)						ELL3(1)	P2RY10(8)	TREML2(4)	SBK1(2)		STK17B(5)	SELL(6)	B3GNT5(3)	LTB(8)		RGS13(2)						IL5RA(2)		KLHL14(1)			IKZF3(5)	ZC3H12D(1)						GPR171(7)							TBC1D10C(7)	
Clara(1)   :0000158(1)		LRRC26(3)	SLC10A5(1)	GABRP(2)	GPX2(3)	RIPK4(3)	LHFPL1(1)	TMEM210(1)			PAX9(1)	SCGB1A1(1)		GSTA2(4)	SCGB3A2(2)	PLCH2(1)	KCNK1(3)	BMPR1B(2)	CATSPER4(1)		DLX4(1)			REG3G(2)	FZD10(2)			AQP4(4)			S100A14(3)	OTX1(1)		LY6G6C(3)	ADIG(1)	FAM83B(1)	CHST9(1)	PPP1R14D(1)	DNAJC5B(1)	DMRT2(1)			FMO3(2)	SLC16A11(2)	DLK2(3)		BPIFB1(1)	CNKSR2(2)	KLHDC8A(1)	REEP6(2)	ALDH3A1(1)			LGR6(1)		FOXA1(4)	LAD1(2)			UPK2(3)	ACSM1(1)	MGST2(3)	GDPD2(2)	LYPD2(2)		GPR87(1)	SIX2(2)	YBX2(1)	SOX21(2)	RPTN(1)	SOX2(2)	ADAM28(3)	BPIFA1(1)	RAC3(1)	SLC25A21(1)	
   :										KLHL6(2)															PMEL(1)	TNFAIP3(5)			RASAL3(5)		GIMAP7(7)				ACP5(3)	GRAP2(3)	CTLA4(3)			B4GALNT1(2)		ICOS(6)					FAM78A(1)			VPS37B(4)	IPCEF1(2)			INPP4B(5)					GPR183(5)						CD40LG(5)				CXCR6(6)					SIT1(1)	SCML4(1)					PGLYRP2(1)		
Ciliated(1)   :0000064(1)		CCDC113(2)	MEIG1(2)	IQCG(1)			TMEM212(2)	SNTN(1)	SPATA18(2)	UBXN10(2)	DYDC2(1)	CCDC153(2)	CCDC40(1)	LRGUK(1)	FAM47E(2)	PPP1R36(1)	CCDC103(1)	LRRC34(2)	EFCAB10(3)	TTC29(2)	STK33(2)	TEKT1(2)	TEKT2(1)	TEKT4(1)	CCDC33(1)	CCDC30(1)	RSPH4A(2)	SPAG8(2)	NEK5(1)	SPAG6(2)	LRRIQ1(2)	VWA3A(2)	FOXJ1(2)	LRRC43(1)	TMEM232(1)	MORN5(1)	AGBL2(1)	CDHR3(2)	MAK(2)	SYT10(2)	NEK11(1)	CCDC60(1)	SPAG17(2)	FANK1(1)	CCDC121(1)	SPEF2(2)	AK7(2)	AK8(1)	DNALI1(1)	IQUB(1)	LDLRAD1(2)	AGR3(2)	TSNAXIP1(1)	
Dendritic(1)   :0000451(1)					ITGA4(2)	SEMA4D(2)					TNFRSF1B(1)							TLR7(4)			CD244(3)			ARHGEF10L(2)			STAP1(4)				SLC16A3(5)	CYTIP(8)	S1PR5(5)	IL17RA(1)		RAP1GAP2(1)								FMNL1(3)				SMPDL3B(1)	MYO1G(4)							CX3CR1(4)			ENO3(1)	SAMSN1(2)			STK10(2)	CXCR4(4)	PGLYRP1(5)	TGM3(2)	LAIR1(3)	
   :		DUSP3(3)		JUP(1)				LYVE1(2)		BST2(2)					SLCO2A1(2)			MYZAP(1)	CD200(6)	ACVRL1(2)	EPAS1(5)				HILPDA(1)	HPGD(2)									EFNB2(3)							S100A16(1)	PLLP(2)		AFAP1L1(3)	SEMA6A(2)	LRRC8A(2)				FMO1(1)		SMAD6(1)	FKBP1A(1)		EHD4(3)		RIPPLY3(2)		TCN2(2)	TSPAN18(1)			RAMP2(4)						SEMA3F(2)				CRIP2(2)							HYAL2(1)								
   :0000066(3)			TTC16(1)		NME5(1)			LRRC23(1)			ITPKA(1)		ZMYND10(1)		TTLL9(1)		KNDC1(2)	ATP2C2(2)							PPP1R32(1)	GAS2L2(1)	CCDC17(1)	SYT5(3)		CDKL4(1)			ANKRD45(1)				KIF27(1)	RP1(1)			CCDC65(1)	RSPH1(1)		LRRC10B(2)	LHB(1)		AKAP14(1)			HYDIN(1)	KCNMB4(1)			
  :		CCR1(5)	FOXD4(1)	MMP8(2)		IL1R2(4)		OSM(3)						BST1(3)						S100A9(3)	S100A8(3)				HP(5)		LMNB1(3)		CXCL2(3)	RETN(1)	SLC40A1(5)			TREM1(3)	HK3(2)		RDH12(2)				CD300LF(5)			SLC32A1(1)	ARG2(2)		ASPRV1(2)			MXD1(3)	NLRP12(2)		TARM1(2)		PADI4(2)	SFXN5(3)	CD101(1)		IL1RN(5)							LILRA6(6)	TRPM2(2)	CXCR2(3)		
 Neuroendocrine(1)   :1000223(1)		SRRM3(1)	RUNDC3A(1)			KCNIP2(1)	LHFPL5(1)	MYT1(3)	GRIN1(2)	LRFN5(1)	SNPH(1)	DAB1(1)	RBM24(3)		GABRB3(1)	HCN4(1)	ZCCHC12(1)		KCNC1(1)	TPH1(2)	SLC35F3(2)	FRMPD3(1)	CIB3(1)	FUT1(1)	DLL3(2)	SHD(1)	ELAVL4(1)	ASCL1(2)	UNC80(2)	TCEAL6(2)	GDAP1L1(2)	HRH3(1)		WNT3(3)	PROK2(2)	PIRT(1)	C1QL1(2)	KCNK10(1)	CASR(1)		DMRT3(1)		ACTL6B(2)	CNPY1(2)	PRSS37(1)	CARTPT(1)	POU3F4(1)	GPR142(1)	PRSS41(1)	CLDN6(1)	TBX15(1)	WEE2(1)	PNOC(1)	VGF(3)	TMEM117(1)	CLDN9(1)	TCERG1L(1)		IGSF1(1)	HCN1(1)	FGF13(1)	HCN3(1)	CDK5R2(2)	CALCB(1)		CLSTN3(1)	CALCA(1)	SLC35D3(2)	STMN3(1)	FMN2(1)	JPH1(1)	CES5A(1)	CST6(3)	FGF5(1)		SOX1(1)	CDH22(2)	CTNNA2(1)		FFAR2(3)	ATCAY(1)	NEFH(1)	
Macrophage(3)  :0000235(3)				CCL22(1)	PHF11(1)		IL18(1)	TRPV2(1)	CD200R1(2)	FNDC7(1)			ITGAE(1)		TNIP3(4)	DCSTAMP(1)							CD80(2)			TSPAN33(2)	CLDN1(2)	DOCK10(2)	PAK1(1)							PPFIA4(3)	XCR1(1)		CARD11(3)	CAMK1D(3)	ATP8B4(1)	MAP4K1(3)			GPR33(1)			KMO(2)	CCDC88B(1)		EVI2A(6)	GATM(2)	PKIB(2)		RYR1(2)	FLT3(3)							IL1RL1(2)	GNA15(2)	RASSF4(7)		TNNI2(1)			BCO2(1)	CCL17(2)	
Mesothelial(1)   :0000077(1)			LRRN4(1)	BDNF(2)	CYBRD1(1)	SHISA7(1)	SLC5A8(1)	WT1(3)	FRAS1(1)	CLDN15(2)	LANCL3(1)	PLXNB3(1)	FXYD7(1)	RPP25(1)	HRG(1)	CCDC150(1)	NFE2L3(1)	KCNK7(1)	MCTP2(2)	SYNPO2(2)	ONECUT2(1)	ILDR2(1)	FOXO6(1)	KIF17(1)	RS1(1)	NPAS3(1)	GRIP1(1)	SNTG1(1)		FLRT1(1)	ZDBF2(1)			RNF112(1)	KCND3(2)	GFRA4(1)	UPK3B(2)	FRMD3(1)		PSRC1(2)	CDH12(1)	COL6A5(1)	BIRC7(1)	SCRG1(3)		XKR4(1)	CHST4(2)	CRB2(1)	TMEM151A(2)	MSLN(1)	COL11A2(1)		MYOM3(2)	KCNV2(1)	JPH4(1)	CUX2(1)	SLITRK4(1)	RSPO1(1)	
Monocyte(2)  :0000576(2)			APOBEC1(4)				F10(3)								TNFRSF21(1)				TLR8(5)				CD177(2)								PSTPIP2(2)												ADAP1(3)								PLBD1(9)														PLAC8(3)			
Natural(4) Killer(4)   :0000623(4)		EOMES(4)	KLRC3(3)		XCL1(6)	CD160(6)	CMA1(3)	LAX1(2)	SYTL3(6)				TMSB15A(2)			DMRTA1(1)	NCR1(3)	IFNG(5)							SLC44A5(2)							ACAP1(4)	KLHL30(2)			ADAMTS14(4)	GPC1(1)	TBX21(6)	PHACTR3(2)		IL12RB2(3)		SAMD3(4)		GZMB(5)		GZMA(3)		KCNAB2(1)								PPM1J(4)			IL18RAP(2)					TNFRSF9(4)	KLRC1(5)	KLRC2(4)	TIGIT(4)	KLRG1(2)		
   :								INMT(3)		LAMB1(2)		PLXDC2(3)	DKK3(6)																SPARCL1(2)				RBMS3(2)			PRDM6(1)				NDRG2(4)		GPC3(4)						MAMDC2(1)	FOXF2(2)							IGSF10(2)	TBX4(1)							NOX4(1)		ANGPTL4(1)			FBN1(5)								LAMA4(2)					ISM1(2)		ADAMTSL2(1)	FGF7(1)		C7(3)						SCARF2(2)	
 I(1) Pneumocyte(2)  :0002062(1)		CCDC112(1)		CACNA2D4(1)	ADAM32(1)	SCNN1G(2)	FXYD3(3)			ACOT6(1)	FRMPD1(1)	GRAMD1C(1)	HMGCLL1(1)	NXPH3(1)	CCDC149(1)	SLC1A1(2)	RNF39(2)		TGFA(1)	PRSS48(1)	SCEL(1)	NT5E(2)	PARD6B(1)	FLRT3(1)	KIF5C(2)		CAP2(2)	TMOD1(1)	MYO16(1)	MPP4(1)	CDKL5(1)	WNT10B(1)	WNT3A(2)	USP44(1)	PSPN(1)		WNT7A(1)	PBX4(1)	SLC6A14(1)	ZBTB32(1)	IL17RE(1)		KLF8(1)	RCAN2(1)	CDCP1(3)	MAS1(1)	TMEM116(2)	NMNAT1(1)		RAB17(1)	POPDC3(1)			ARHGAP8(1)		ITGB6(2)	CTTNBP2(1)		SEMA3E(2)	RTKN2(1)	MIA2(1)	PRKAG3(1)	SH3RF2(1)	NUDT12(1)		GPAT2(1)	ANXA9(1)	ERC2(1)	TRPM6(3)	
 II(1)   :0002063(1)		SFTPB(1)	EGFL6(1)	SFTPC(1)	ARHGEF38(1)				KCNJ15(2)	ETV5(1)		EPN3(2)	PTPRF(2)	SLC26A9(1)	CLDN18(1)	PRR15L(2)				RET(2)		LRP2(2)	TFCP2L1(2)	KCNC3(1)						BAIAP2L1(1)		SEC14L4(2)	DRAM1(2)	CDH1(6)	LAMP3(1)			NKX2-1(2)		SLC39A8(1)	CLIC3(3)	TINAG(1)	S100G(2)		IRX3(2)		CHIA(1)	PRMT8(1)		SLC34A2(1)	IRX5(2)	LGI3(2)	SNX25(1)	RAB27B(2)	MYO5B(3)	ANK3(2)	SCGB1C1(1)		FASN(1)	SLCO4C1(2)		OCIAD2(2)	SDC1(2)	MET(2)	SFTPA1(1)				FOXA2(1)			KCNE2(1)	BEX2(1)	SFTA2(1)		WWC1(3)	MLC1(3)		AGER(2)	PPP1R9A(1)	C6(1)	ACOXL(1)	NPW(1)	ATP7B(1)	ATP6V1C2(1)	
  Fat(10) :														REL(1)																																					B3GNT7(4)									FAM107B(2)													CNR2(1)							
   :		DUSP5(3)																								GIMAP1(1)												GIMAP8(2)				DUSP10(1)		TNFRSF18(5)			CCR8(3)																										FAAH(2)									GPR132(6)	TESPA1(3)	TNFSF11(1)						
   :																																HSPB1(3)																																					PDGFB(2)																	
   :		TFAP2B(2)			R3HDML(1)	MACC1(1)					GRHL2(2)					GIPC2(1)	ESRP1(2)		SERINC2(3)		ACOT1(1)		CDO1(3)	IDO1(1)	TFAP2A(1)	SLC44A4(1)	CITED1(1)								MTMR7(1)	SLC5A5(1)	CXCL17(1)				CAPN8(1)				MSX2(2)	MPZL2(2)	AP1M2(2)	FGG(2)	ARHGEF16(1)			ESRRG(1)		PROC(1)					FAM131C(1)			CDH16(3)	DYNLRB2(1)	GRB7(1)			CAPSL(1)			RASEF(1)				TMEM102(1)	SPTLC3(1)	RASSF6(2)	PROM2(1)	TSPAN1(3)	PLS1(2)	PROM1(3)		
Granulocyte(2)  :0000094(2)			CCL24(3)				PLA2G2D(1)						TMEM37(1)				SIGLEC1(3)	NINJ1(1)		FXYD2(3)					DCLRE1C(1)				CLEC10A(4)			P2RY6(2)						CD33(2)		TPD52(2)	MARCKSL1(1)	SUSD1(1)			SERPINB8(1)	ADAP2(3)		RBM47(3)			C1QC(2)			C1QB(1)	C1QA(2)					NPL(3)	ARRB2(2)	AOAH(1)						LTC4S(4)						
   Of(7) Adipose(1)  :0002570(1)			GABRA3(1)							OSR1(1)																												EGFR(1)										PAMR1(1)	POSTN(2)																PI16(2)										SEMA3C(5)								C3(3)						OLFML1(1)			
   :							ETV3(1)				UPB1(2)				DPEP2(4)											FGD2(1)					CYSLTR1(2)												TRAF1(3)							EVI2B(1)		ALDH1A2(1)		UNC119(1)							DOCK8(1)	CLEC9A(2)								ALCAM(3)					
    :								BAIAP3(2)											CLNK(1)														CYSLTR2(2)							STYK1(2)							SERPINB9(2)															CXCR3(5)									
Neutrophil(2)  :0000775(2)							ARHGEF37(2)									RNF149(1)																																														SLC2A6(2)					
    :		PCP4L1(3)	KCNJ12(2)			TESC(3)	NPY1R(2)	TRPV1(1)	CCK(1)			SCN4B(2)		RGS7BP(1)		CCDC3(3)			ASB2(2)				KLHL38(1)				GPR20(3)		AKAP6(1)		KBTBD13(1)	CDH6(1)				SUSD5(2)		RNF152(2)			PRKG1(1)				LHCGR(1)	STAC(1)				KCNAB1(1)	SCTR(1)	SORBS2(1)	CACNB2(1)									SLC22A3(2)	RERGL(1)	SLC22A2(1)		FHL5(2)	CABP1(1)	SLC2A4(2)	PPM1L(1)		FGF1(1)			JPH2(2)		CRHR2(1)					HEY2(2)				CTNNA3(1)			
  Trachea(4) :																				RAPGEF5(1)		CSF3(1)								FUT2(1)						GNGT2(1)																					SELP(1)				NOTCH4(1)						RND1(1)																		
   :					DIO1(1)			KCNJ16(1)										PAX8(1)								CELSR1(2)				SCNN1A(3)		C2CD4B(1)					SEC14L3(1)	FAM83H(2)	IYD(1)		UPK1B(2)										WNT4(1)		KCNH3(1)			STARD10(2)									TSPAN15(1)								CASZ1(1)	FOXE1(1)		LAMA5(3)						SLC4A5(1)		TPO(1)			NPY(2)	RASSF7(1)	FAM110C(2)			
  :																NEURL3(1)					NFKBID(2)										TNF(1)			GNG2(2)																				TM6SF1(1)															PTAFR(2)	KCNA3(1)											GLIPR1(2)				PTK2B(2)		
   :				TGFB3(1)				CRTAP(2)					TGFBR3(1)												FKBP9(1)	CALU(1)				PPIC(3)	FKBP7(2)		NFIX(2)	CHPF(2)		SERPINE2(2)			ZBTB20(1)	ANTXR1(3)	LAPTM4A(1)	BOC(1)			TIMP3(2)		TIMP2(3)		CLEC11A(1)	PRNP(1)			FNDC3B(1)	NFIA(1)	RNASE4(3)	VASN(2)	GEM(1)	CKAP4(2)		KLF9(1)	TWSG1(1)								CD302(3)	RECK(1)	ITM2A(2)				CD63(3)	SPARC(4)	FKBP10(2)	ECM2(3)					LTBP3(2)			LTBP4(4)	PKD2(1)				IGFBP7(4)				
   Epidermis(3) Tongue(2) :0002187(2)		SLC12A4(1)	PAICS(2)			ITGA3(2)				MORF4L1(1)	UGDH(2)			MTHFD1(2)	S100A6(4)	RNF141(1)		MYADM(1)			PLEC(1)	CALM2(1)		TLN1(1)	AGRN(2)	PTPRS(2)	IFITM3(5)		CCNI(1)	HMGB1(1)	NEDD9(1)	LAMC2(2)	PDLIM1(1)			SH3BGRL(2)	CASP6(1)					RBBP8(1)	S100A10(1)	KCNH1(2)	HMGN2(1)	IGFBP2(2)	TGIF1(2)		JAG2(2)	DST(1)		PAPPA(2)	SOD1(1)		SLC6A6(2)	EHD2(1)			PPP2R2C(2)	PROCR(1)	CDH13(3)			OAT(2)		ITGB1(1)				ITGB4(3)		PTN(2)			CRIP1(3)		TMSB4X(2)		SPRED2(1)	RPS6KA1(1)	SCMH1(1)		FTH1(1)		TSPAN3(2)	TSPO(1)			CTNNAL1(1)	
Keratinocyte(2)  :0000312(1)			SPINK5(2)	FGFBP1(2)	KRTDAP(2)		ACSL1(2)	TREX2(2)		GRHL3(3)	CNFN(1)	MT4(2)	PDZK1IP1(3)				ABCA12(3)		RBP2(2)	GSTA1(1)	PIR(1)			CLDN17(1)		PKP1(2)	TTC22(2)			ANKRD35(1)		CALML3(2)		DBI(3)			SBSN(2)		PYCARD(1)					ME1(3)			RHBG(1)	SDR16C5(1)	FDPS(1)	PSAPL1(1)	PLA2G4E(1)	PLA2G4F(2)		MOCOS(1)	ELOVL4(2)		LSS(1)	KRT32(1)	TMPRSS11D(1)	FOXN1(1)		SULT2B1(2)	DLG2(1)	ACER1(2)			EFNA3(1)		SPRR1A(2)	SPRR1B(1)		GLTP(2)	FAM25C(1)	LYPD3(2)	PPL(1)	DMKN(1)			TGM1(1)			ALDH3B2(3)	BAG2(1)	THEM5(1)		
    Skin(4) :		TFAP2C(2)		IPMK(2)			SOX15(1)			WNT16(1)			BHLHE40(1)					PHLDB2(1)				LRP4(2)		GPT(1)	ASCL2(1)		DLL1(2)	APCDD1(1)		SCIN(1)	CDH4(1)			CHL1(3)	TRIM47(1)	CPXM2(1)	EXPH5(1)			NGFR(1)	CARD10(1)	IL33(2)	SERPINB2(2)		SLC2A12(1)	IFNGR1(1)			KLF5(3)		SERPINB7(1)	FBXO32(1)		IL22RA2(1)	CHIT1(2)	WEE1(1)					SLC24A3(1)		HLF(2)		SLC22A4(2)	SEMA3D(2)	MAPKBP1(1)					PRICKLE1(2)	IKZF2(2)					HERPUD1(3)	SLC6A4(1)	GNA14(1)	FOXQ1(3)	CUX1(2)		IL20RA(1)	CLCA2(2)	MAN1C1(2)	GLUL(1)		SOX6(2)	
Epidermal(1)   :0000362(1)		RARRES1(1)	KRT1(1)				ANXA1(2)		BBOX1(1)				KRT10(1)		KLK11(1)		NME1(1)					ANKRD22(2)	TRIM16(1)		NHP2(1)					HPGDS(2)	CASP14(1)					B2M(1)		HMGN1(2)	S100A11(2)			PAQR5(5)				ELOVL7(1)	KRT77(1)		OVOL1(1)		GGCT(1)					SLCO3A1(3)		ACSBG1(3)	HBEGF(2)				AK2(1)						CNN2(1)			LIPM(1)				
    :0002337(1)				KLHL29(1)		MITF(1)	NFATC1(1)		FOXP1(2)	SHISA2(1)	ID3(2)			IL31RA(1)		VWA2(1)			KCNK2(1)	PFN2(1)		PDZRN3(1)	PDZRN4(2)			APP(1)		CITED2(1)	ADCY1(1)	SCX(1)	KRT24(1)		PTPRK(1)	AQP3(2)				KRT6A(1)			FLNB(1)			NFIL3(1)		FZD2(2)		FZD1(2)	TBX1(1)	FZD3(1)	DAPK2(1)	FZD7(1)		GFRA1(1)	MN1(1)	FGF18(1)	FAM167A(3)	GREM1(1)			LHX2(2)	SARDH(1)			PI15(1)	COL8A2(1)	ESYT3(1)		MFGE8(1)					USP54(1)				CHAT(2)			BARX2(1)		NUDT4(3)				ADAMTSL4(1)			TGM5(1)		
     :1000428(1)			ESCO2(2)	CDC20(1)	CDC25C(2)	CENPE(2)	ANLN(2)	CENPF(3)	MELK(2)	NEIL3(2)	CENPI(1)	BUB1B(2)	CENPK(2)	CENPM(2)	CDK1(2)	KIF20A(1)	KIF20B(2)	MAD2L1(1)	ASF1B(1)	CDKN3(2)	ANKLE1(2)	SKA1(2)	KIF11(2)	PIF1(2)	TOP2A(2)	AURKA(2)	NCAPG(1)	KIF15(1)	HMMR(2)	CCNF(1)	KIF14(1)	NCAPH(1)	IQGAP3(2)	AURKB(2)	MIS18BP1(2)	RACGAP1(1)	PBK(2)		ECT2(2)	GAS2L3(3)	CEP55(2)	DLGAP5(2)	PRR11(1)	PLK1(2)	KIF22(1)	SPAG5(2)	CKAP2(2)	KIF23(1)		SHCBP1(2)	NDC80(2)	ASPM(2)	CCNA2(1)	SPC24(3)	TPX2(2)	KIF18B(2)	KIFC1(2)	BIRC5(3)	NCAPD2(1)	TROAP(2)	KIF2C(2)	TACC3(1)	MXD3(2)		CDCA2(2)	ARHGAP11A(2)	CDCA3(2)	CDCA5(2)	CDCA8(2)	ARHGAP19(1)	MKI67(3)	TTK(2)	CENPA(1)	FOXM1(1)	CCNB2(1)	CCNB1(2)	NUF2(1)	NEK2(2)	NUSAP1(2)	BUB1(2)	BARD1(1)	
  Liver(5) :														IRF4(2)	CLCF1(2)							XYLT1(2)	TSPAN32(1)	AFF3(1)				CTSE(2)																PIK3IP1(1)																									BEND5(1)							
Kupffer(1)   :0000091(1)						MYOF(2)								MARCO(1)			CD207(1)			CLEC4F(1)		ADAMDEC1(1)										TMEM26(1)				GBP1(1)			DMPK(1)						MYO9A(1)		FABP7(2)									KCNA2(1)		CD5L(1)									HMOX1(1)	VSIG4(1)	
  Hepatic(1) Sinusoid(1)  :1000398(1)			PLXNC1(1)			BMP2(1)		DAB2(2)					AMOTL1(1)	ITGA9(2)		IL6ST(1)	CLEC4G(1)		NPR1(2)		PLXND1(2)			TFPI(2)																				MAF(2)			F8(1)	EHD3(3)		HSPG2(2)	COL4A1(2)					COL4A2(1)	DLC1(2)				DNASE1L3(1)	PLEKHG1(1)			NRP2(1)					SLC43A3(3)							ELK3(2)									STAB2(1)			C1QTNF1(4)	OIT3(1)			
Hepatocyte(1)  :0000182(1)		GPX1(1)	PHYH(1)	HMGCS2(2)	GSTM1(2)	AMBP(1)		APOA2(1)		FAH(2)	ASS1(2)		BHMT(1)			ALB(2)	APOA1(1)	ACOX1(2)		ALDOB(3)	OTC(2)			ALDH1L1(2)	ADK(1)		TAT(1)	HAAO(2)		CROT(1)		KNG1(1)	C8G(1)	SEPHS2(1)	PCK1(2)	FGA(1)	SLC25A47(1)	FGB(1)						EPHX2(3)								MAT1A(1)		TST(1)	APOC3(1)		ANGPTL3(1)	RGN(1)	HPD(2)	HAMP(1)	CYP2E1(1)	GCDH(2)	FABP1(2)	AHCY(1)	ORM1(2)	SERPINC1(1)	UROC1(2)		NUDT7(1)	HPX(1)		DDT(1)	CBS(2)		TDO2(1)	SCP2(1)	APOH(1)		METTL7B(1)	ACAA2(1)	MBL2(1)	
    :																						BCL2(2)													ABCB9(1)									PSTPIP1(1)													CCDC136(1)		TMEM154(3)						EVL(2)				PADI2(1)		ARHGAP9(2)	ATP8A2(1)		PTGER4(1)						PODNL1(2)									
   :					SP110(1)																																																																									
   :																		TNFSF8(1)			TNFRSF25(2)					SLAMF1(1)													IL27RA(1)							S1PR4(1)								ST8SIA1(1)																										CHRNE(1)									
   :						LMO7(1)										RAPGEF3(2)																																								TNFRSF10B(2)		RNF125(1)					LNX1(2)	B3GNT3(1)																					LRRC8C(1)					
  :																								MCTP1(2)		EBI3(1)			PIK3R5(2)																																															
    :													DNM1(2)	DCLK1(2)				VCAN(4)														STEAP3(1)							FBLN2(1)					DPYSL3(2)			LBP(1)		MYOC(1)							ABCA9(1)		F3(2)						OAF(2)									ANGPTL1(1)																				
Skeletal(1)  Satellite(1)   :0000594(1)				RPS8(2)	HSPA5(1)	RPS9(1)		TNFRSF12A(1)	RPS6(1)	RPL23(1)	RPS7(1)	SYTL2(4)		MYOD1(1)	RPS3A(1)	VCAM1(1)			CRLF1(1)	EEF1A1(1)		RAPSN(2)	ASB5(1)		SRSF5(1)	FXYD6(2)	TLN2(1)	CHRNB1(1)			ODC1(1)	RPL13(2)		DRP2(1)	LMNA(2)			BDKRB1(1)	RPL36A(1)	PDE4B(1)	RPS5(2)	RPL14(1)	FLNC(1)	RPL17(1)	MUSK(1)	RPS3(1)	RPL18(1)		F2R(2)	PDE4D(1)	ARID5B(2)		SLC39A14(1)	HEYL(2)		FOSL1(1)	MYL12A(1)	UCK2(1)	RPS28(2)			CDH15(1)	RPS23(1)		MYF5(1)	TRIB1(1)	ERRFI1(1)		RPL6(1)	RPL31(1)		EIF4A1(1)	RPL3(1)	RPL4(1)	CHODL(1)		RPLP0(1)	RPL32(2)	INSIG2(1)	RPL10A(2)	RPL9(1)		RPL7(1)		RPS4X(1)	CALCR(1)	RPS18(2)	RPL18A(1)		RPS19(2)		RPL37(1)	RPL36(2)		RPS14(1)	
   Urothelium(1) Bladder(4) :1000486(1)		CDK18(1)					ACSL3(1)						CHKA(1)			ITGA2(2)	TRPV4(1)			ALDH6A1(2)	PKP3(1)			EPHA2(2)			TRIM13(1)		NRN1(1)		ZFAND2A(1)	GMPR(1)		ATP1A1(2)			FAM83G(1)	SHH(1)		HAS3(1)	CAPN1(1)	RALGDS(1)	LDLR(1)	SERPINB5(1)			PHC2(1)	FZD6(1)	PLEKHG6(2)	UNC5A(1)	EEF2(1)			TBC1D1(1)			TTC9(1)			GCLC(2)	PFKL(1)	RNF128(2)	NET1(1)	SGSM3(1)			FSCN1(2)	EZR(2)				PXN(1)		CTNNB1(1)		PAPLN(1)	SLC2A1(1)			HIF1A(1)	PRSS22(1)	GPNMB(1)			CLCA1(1)		JAK3(1)	TNS4(2)	SH2D5(3)	
   :1001319(1)		GSTM4(1)					SYTL1(1)				UPK1A(1)											ALPL(1)						DEGS2(2)		TMEM45B(1)					SNX31(1)				UCHL1(1)												LSR(2)	FMO5(2)		UPK3A(1)	SYT8(1)								EBPL(1)				IVL(1)				MGST3(1)										VSIG2(1)		GPA33(1)	SRD5A1(1)		SH3GL2(1)	
   :0008019(1)						EMP3(1)		RHOC(2)																RHOJ(1)	VIM(1)												COL12A1(1)						DPYSL2(2)							WNT2(1)				GADD45G(1)								KDELR3(2)																				FCGRT(1)	NKAIN4(2)		AKAP12(2)							LGALS9(1)		
Brush(1)   Epithelium(2) Colon(5) :0002203(1)		PCDH20(1)	MATK(1)	POU2F3(1)	GNG13(1)	AGT(2)						GFI1B(1)	OAS2(2)	SIGLEC5(1)	HAP1(1)	HMX3(1)	HMX2(1)	SUCNR1(1)	CCNJ(1)		ADCY5(1)	AVIL(1)			TMEM121(1)			GNAT3(1)		RGS22(1)		LY6G6D(1)	LY6G6F(1)	ST18(2)		NEBL(1)		PROX1(2)			IL17RB(1)		TNNT2(1)	DMXL2(1)			PLEKHO2(1)	TRIM38(1)					DGKI(1)		PFKFB3(1)	CRISP3(1)		CAMK2B(2)	IL25(1)			SEZ6L2(3)			NRGN(1)			PIK3CG(1)			OGDHL(1)	NEFL(2)		FFAR3(1)			SH2D7(1)		
Enterocyte(1)    :0002071(1)					SLC10A2(1)	EMP1(1)		LHFPL2(1)	GTPBP2(1)	SDCBP2(1)				SULT1B1(1)		TMIGD1(1)						IRF7(1)	SGK2(1)		ABCG2(2)	IGSF9(2)			ENDOD1(1)		KRT20(1)	SLC9A2(1)		PTPRH(1)		PRAP1(1)	NEU1(1)		CEACAM20(1)	SPRR2B(1)	PPFIA3(1)	SLC13A2(1)	PHGR1(1)	UNC5B(1)	CDKN2B(1)				SELENBP1(2)	GUCA2A(1)	FA2H(2)		MEP1B(1)		CDHR2(1)	HKDC1(1)	MGAT4C(1)		CDHR5(1)	MEP1A(2)	SAA1(1)	MAPRE3(1)	SLC26A3(1)	PHLPP2(1)		ESPN(1)	TMEM140(1)	SLC30A10(2)		LIPA(1)					APOB(1)	
Enteroendocrine(1)   :0000164(1)				KCNB2(1)		CADPS(1)	CACNA2D1(1)		PAX4(1)			VWA5B2(1)	SSTR5(1)	DISP2(1)	GCK(1)	OLFM1(3)		ASPHD1(1)		GNAO1(1)	RFX6(1)	GPRIN1(1)		RIMBP2(1)		LRP11(1)		SCG3(2)	STX1A(1)	SNAP25(2)			SHC2(1)	CELF3(1)		PTPRN(1)	ADCY2(1)	GOLGA7B(2)	GNG4(1)	KIF1A(1)		NKX2-2(1)			RPRML(2)	HMGN3(1)	GPRASP2(1)	RUNX1T1(1)	NEUROD1(1)					SYP(1)			FBXL16(1)			ARMCX2(1)	SYT13(1)	LMX1A(1)	PRKAR1B(1)			GNAZ(1)			NRSN1(1)										DNER(1)		KCNMB2(1)					RGS7(1)	
  Large(2) Intestine(2)  :0002253(1)		EDN1(1)		GSTM3(1)					LIG1(1)	RPL13A(1)	ATAD3A(1)	NAP1L1(1)	HSPE1(1)	RPSA(1)	VAV3(2)		PTMA(1)		RPL37A(1)		MCM6(1)	RPL28(1)	SNRPF(1)					RPL12(1)	SHMT1(1)		HMGB2(1)			CSRP2(1)		SNRPD2(1)		NLRP6(1)		HAO2(2)	RPS2(1)	CCDC34(1)			NQO1(1)	HELLS(1)		MIF(1)	RPL35A(1)	ANO6(1)		RPS26(1)		LSM7(1)	MYBBP1A(1)			NOXA1(1)					CD44(1)		NOTCH1(2)	ISYNA1(1)		SLC22A1(2)		ACSM3(1)	RPL35(1)					HSPD1(1)	RPL8(1)			RPS15(1)								RPS12(1)	CLCA4(1)	
  Goblet(1)   :1000320(1)				SPINK4(1)	TTC39A(1)	GALNT7(1)	GALNT5(1)	PLA2G2F(1)			SLC50A1(1)	ERN2(1)						TFF3(1)	KCNK6(1)	GALNT12(1)	REP15(1)		TNFAIP8(1)					RAP1GAP(2)	GALNT10(2)	BEST2(1)	FUT4(1)		CREB3L1(1)			RASD2(1)	CREB3L4(1)	QSOX1(1)	ST3GAL6(3)	BCAS1(1)	SLC12A8(1)	TRIM46(1)		ATOH1(1)	CGREF1(1)	XBP1(1)	ST6GAL1(2)	TPSG1(1)				ANO7(1)		COPZ2(1)	PDIA5(1)	SYT7(1)			P2RX4(1)			A4GNT(1)	REEP5(1)	KCNMA1(1)	ASPH(2)					FOXA3(1)		RAB3D(1)	FKBP11(1)			CXXC5(2)	ABO(1)				TXNDC5(1)		REG4(1)		AGR2(1)	SYBU(1)	
  Marrow(8) :			MAP3K1(1)				PLEKHA2(1)								MTSS1(1)						MYL4(1)			GLCCI1(1)	PAFAH1B3(1)				BTG1(1)		ZFP36L1(1)	BACH2(1)	FOXO1(1)	ABLIM1(2)			BCL7A(1)																SYVN1(1)		KLF2(3)		PTP4A3(1)			GRAP(2)		TRIB2(1)						CNP(2)					CPLX2(1)		CECR2(1)													
Fraction(1)  Pre(1) Pro(1)    :0002045(1)		HS3ST1(1)	LAG3(2)		LIFR(1)	TEX2(1)			RUNX2(1)			RPGRIP1(1)			RTN4RL1(2)		ITGAD(1)		PLEKHM3(1)		CD300C(1)				DDR1(1)			AHNAK(3)				CTNND2(1)			LRP8(1)	XKRX(1)					CTSL(2)				HAVCR1(1)	PACSIN1(1)		SH3BGR(2)		LEFTY1(1)		ADAM11(1)		ZDHHC14(1)			FBXL13(1)	EEPD1(1)	FOXR1(1)		CHDH(1)	NUCB2(1)		APBA1(2)	TMEM229B(1)	SLC41A2(1)		ATP2A1(1)	RND3(2)	PTMS(1)	TMEM221(1)	PDZD4(1)	GRM8(1)	ZC3H12C(1)		HIVEP3(1)		SRGAP3(1)		
   :					CRTAM(2)																	MS4A2(1)						ALOX15(1)											HRH4(1)				FCER1A(1)																										GPR174(2)											
  :					DUSP1(2)																			GRINA(1)																								FOSL2(1)							LCN2(2)		ANKRD33B(1)		CEBPB(1)				SLC2A3(1)					RASGRP4(1)			MMP25(2)			
Hematopoietic(1)    :0000037(1)			HSD3B7(1)					DNMT3B(1)	HMGA2(1)	NME4(1)	ABHD14A(1)	DEF8(1)	OTOS(1)	SIRT3(1)		ARHGAP32(1)	G6PC3(1)	MEIS1(2)	CDK6(1)	RAB38(1)	DNAJC6(1)			TFR2(1)					ABHD4(1)	MPL(1)		SDSL(1)	SYCE2(1)	HOXA9(1)		MYC(1)	MYL10(1)	SMYD2(1)	HOXA7(1)	LZTS2(1)			GABARAPL1(1)	TMEM176A(1)	KCNK12(1)			TMEM176B(1)	KCTD1(1)		SORBS3(1)			DCTD(1)		MC5R(1)			SSBP2(1)		F2RL3(1)	RANGRF(1)	OSBPL1A(1)		MDGA1(1)			CAMK2A(1)	GCNT2(1)			RHOBTB3(1)	REPIN1(1)	GCSH(1)		MUC13(1)			TSPAN4(1)		
  :								ANXA5(1)						ADORA2B(1)		NAAA(1)						TMEM106A(1)									PIK3R6(1)		PSAP(1)		DSE(1)			STOM(1)		STXBP6(1)				GALNT9(1)								HPSE(1)						PLCB1(1)		PID1(3)		KRT80(2)													IL13RA1(1)	
    :																																																												QRFP(1)										
  :			ANXA3(2)	GCA(1)			MAPK13(1)	MTUS1(1)					PPP1R42(1)	MEGF9(1)	RHOU(1)							SGMS2(2)	ABHD5(1)		MOGAT2(1)							ST3GAL5(1)		CAMP(1)		DGAT2(1)			INHBA(1)	TEX15(1)					TNNT1(1)						CEBPE(1)		ADPGK(1)				SYNE1(1)		LY75(1)	GPR84(2)			ABCA13(2)	TNFSF13B(1)		GOLIM4(1)		NHSL2(1)		PRDX5(2)	CLEC5A(1)	ALDH3B1(1)				CPA6(1)	OLR1(1)	
 Brain(13) Microglia(2) :											L1CAM(1)	MOB3B(1)										RARA(1)			PDE7B(1)	RGS18(1)	IFITM2(1)		TRPS1(1)	NLRC4(1)	IQGAP2(1)	SAMD9L(1)				SH3PXD2B(1)		CPNE2(1)						MYO5A(1)		TRERF1(1)		B3GNT8(1)	MDFIC(1)		GAPT(1)	CERKL(1)	HIP1(1)									FOXRED2(1)					BEND4(1)		
Microglial(1)    :0000129(1)		MYLIP(1)		CD164(1)		CMTM6(1)	CRYBB1(1)	GOLM1(1)	NAV3(1)		MERTK(1)	TGFBR1(1)	RHOB(2)	TANC2(1)	MARCKS(1)			CD9(1)		SFT2D1(1)			DAGLB(1)	SLC46A1(1)				SLC1A3(2)		TREM2(1)	LRRC3(1)							USP2(1)	ADORA3(1)			CTSF(1)	GAL3ST4(1)			PAG1(1)	P2RY13(1)	COL27A1(1)	P2RY12(1)	LRBA(1)	GPR34(1)				MGAT4A(1)		TMEM119(1)	LGMN(1)		SMAP2(1)				GFM2(1)	SCOC(1)	ITGB5(1)		HEXB(1)	LPCAT2(1)		GNS(1)			SLC2A5(1)			MED12L(1)		ARHGAP5(1)	PHYHD1(2)			SLCO2B1(1)		ABHD12(1)		SALL3(2)		SRGAP2(1)		
  Kidney(8) :								DKK2(1)			IRF1(1)		NUP210L(1)			FAS(1)			HSPA1A(1)					CLIC4(1)		ICA1L(1)				ALOX12(1)					SOCS3(1)		SBNO2(1)			RASD1(1)			KDM6B(1)						PLK2(1)			KLF4(1)	PBX1(2)	TBX3(1)			KLF7(1)			GNB1(1)	PLSCR4(1)					TAF7(1)						CDKN1A(1)		PLAT(1)			ETS2(1)			UBC(1)		ADAMTS1(1)			SERTAD1(1)	IER2(1)		IER3(1)	
Fenestrated(1)   :0000666(1)					HEG1(1)							RAPGEF4(1)		PTPRU(1)						ITPRIP(1)									PTPRG(1)			MEOX1(1)					SH3BP5(1)																				RNF144A(1)			SNRK(1)						VAMP5(1)																									
  :							EPDR1(1)	NFATC4(2)			FOXP2(1)									CCDC8(1)	PDE3A(2)	LRRN1(1)		BMPR1A(1)						LAMC3(2)	MRGPRF(2)						AOX1(1)	PLCE1(1)	GPC6(2)		PDE8B(1)		ABCA6(1)		PPBP(1)	SSRP1(1)	AVPR1A(1)				HSH2D(1)	DPY19L3(1)	ESYT1(1)				FGF10(1)	COL6A6(1)				SPON1(2)		FHL2(1)	WDR86(1)							ROBO2(1)										CEP72(1)			HOXC9(1)	HOXC8(1)	
 Collecting(1) Duct(1)   :1001225(1)		SLC12A3(1)	KL(1)	EMX1(1)				KCNJ10(1)	EGF(1)	S100A1(1)				COX6C(2)		TMEM213(1)		TOX3(2)		TRPV5(1)				CYB5RL(1)	PLCD4(2)	SLC25A35(1)	HOXD9(1)		RHCG(1)	GAL3ST1(1)	COX7B(1)					CLCNKB(1)		CWH43(1)		UMOD(1)				KALRN(1)	HSD11B2(1)			ERMP1(1)	CAPN5(1)		STK39(1)	SLIT2(1)	SLC16A7(1)	ME3(1)		OXGR1(1)						NDUFA1(1)			ATP4A(1)		WNK1(1)		RNF208(1)		LHX1(1)	WNK4(1)	ILDR1(1)		BCAT2(1)		PVALB(2)	PTGFR(1)	TFRC(1)	NDUFA11(1)				SLC8A1(1)			OXCT1(2)			KCNJ1(1)			
 Tubule(1)   :1000507(1)		MIOX(1)				SORD(1)	TMEM174(1)								DNASE1(1)	CHPT1(1)				CRYL1(1)	GAS2(1)			ALDH8A1(1)	SLC22A8(2)		SLC27A2(1)		ACY3(1)	CISD1(1)		SLC5A2(1)	KHK(1)	NDRG1(1)	FUT9(1)	HINT2(1)		SLC22A18(1)	SPP2(1)					SLC22A12(1)	IDH1(1)		SLC17A1(1)			RAB3IP(1)	SLC13A1(1)	SLC34A1(1)			PDZK1(1)		GUCA2B(1)		SOD2(1)	MSRA(1)	BDH2(1)	DDAH1(1)						SLC22A6(1)		PECR(1)	GLYAT(1)	SLC4A4(3)	CRYZ(1)			PTER(1)		MDH1(1)		PCBD1(1)		XYLB(1)	
  :						FNBP1(1)									TLR2(1)	MMP13(1)		MMP12(1)																																													ARHGAP22(1)			PTCHD1(1)					
Bergmann(1) Glial(1)   Non-Microglia(10) :0000644(1)		SLC14A1(1)	CD70(1)	GABRA4(1)	BTBD17(2)	GPR37L1(2)	COX7B2(1)		MYBPC1(1)	PAX3(1)		DAO(1)		SLCO4A1(1)	TTLL3(1)	PM20D1(1)	TNC(1)	LCAT(2)			HK2(1)		WNT6(1)		MDK(1)	OTOA(1)								ELOVL2(2)		WHRN(1)	GRID2(1)	LGI4(2)			SLC39A12(2)		HOPX(1)		TLCD1(2)		CPSF4L(1)	GJB6(2)			CTXN3(1)	PDE9A(1)	LXN(1)			GRIA1(1)	UCMA(1)		ACSM5(1)			DDO(1)			ZIC4(1)		ZIC1(1)				LRIG1(1)	KCNN2(1)		CACNG5(1)	MAP2K6(1)	
Astrocyte(1) Cerebral(1) Cortex(1)   :0002605(1)				ADHFE1(1)		DIO2(1)			ACSL6(1)	MT3(1)		GRIN2C(1)			PPP1R3G(1)		TUBB2B(1)	PPP1R3C(1)		LIX1(1)		CSPG5(1)		ATP13A4(1)		FJX1(1)				GABRB1(1)		SLC1A2(1)								SLC7A10(1)			NWD1(1)	BAALC(1)		GPC5(1)	NTSR2(1)								GABRG1(1)		SLC6A11(1)		BCAN(1)		SLC25A18(1)				CHST1(1)						GLDC(1)	LUZP2(1)	NCAN(1)				DBX2(1)	FAM107A(1)	RORB(1)									PHKG1(1)		AIFM3(1)	TMEM47(1)			PRODH(1)		
 Pericyte(1)   :2000043(1)							WNT5B(1)																				RRAD(1)				NEXN(1)			HSPB2(1)			NTN4(1)	GRIP2(1)	FBXL22(1)	MUSTN1(1)	MARVELD1(1)													WTIP(1)			TBX18(1)	PGF(1)											TGFB1I1(1)	TMEM200B(1)		PDE1A(1)																DHX58(1)		SLC19A1(1)			
    :				ABCC4(1)					TGFBR2(1)	SLC7A5(1)		CXCL12(1)						VWA1(1)					ARL4A(1)					ST6GALNAC2(1)			SGMS1(1)					ATP10A(1)																			GCH1(1)										NOSTRIN(1)								WFDC1(1)													
Neuron(1)   :0000540(1)			SLC12A5(1)	GABRA1(1)		SVOP(1)	DCLK3(1)	NAP1L2(1)	TMEM130(1)				GPRIN3(1)					NAPB(1)			HPCA(1)			CELF4(1)	TRANK1(1)	NRXN3(1)			PHYHIP(1)					SYNGR3(1)	TCEAL5(1)	CAMKV(1)	DLGAP2(1)		BSN(1)		CALN1(1)	SULT4A1(1)		SNCB(1)		ATP6V1G2(1)	SYT4(1)	NTNG1(1)	ELMOD1(1)	SLC6A17(1)				ATP2B2(1)		ANO3(1)	GABRG2(1)	FABP3(1)		RIT2(1)	RAB15(1)		KCNQ2(1)	INA(1)	SCN2B(1)			CPLX1(1)	NRSN2(1)	BEX1(1)	MYT1L(1)	GPR88(1)		DIRAS2(1)		KCNA4(1)	CACNA1E(1)	LIN7B(1)	ENO2(1)	CACNA1I(1)	GRM1(1)			CACNG2(1)	CACNG3(1)	CLVS1(1)		GABRD(1)	RPH3A(1)		
Neuronal(1)     :0000047(1)		CENPW(1)			SOX11(1)		MEX3A(1)					CENPH(1)					SP9(1)	SP8(1)			DLX1(1)			DLX2(1)						CKS1B(1)						CHEK1(1)						GTSE1(1)		CKAP2L(1)	GSX2(1)		STIL(1)	ST8SIA2(1)		PRC1(1)								DBF4(1)				CKS2(1)		DTL(1)									UHRF1(1)										HNRNPA1(1)	
Oligodendrocyte(2)   :0000128(1)					MOG(1)		RHOG(1)	ERMN(1)	MAPK8IP1(1)	LARP6(1)			DBNDD2(1)	PEX5L(1)	CLDN11(1)		TPPP3(1)	CNTN2(1)	MAP6D1(1)	TRIM59(1)			TMEM63A(1)			SLC44A1(1)	GPR62(1)	CPOX(1)		MOBP(1)	ADO(1)	SLAIN1(1)	HAPLN2(1)	AGPAT4(1)	GJC2(1)			TMEM125(1)	PIP4K2A(1)	NKX6-2(1)	TPPP(1)		PTGDS(1)	ABCA2(1)		GPR37(1)	OPALIN(1)	KCNK13(1)			TUBB4A(1)	DUSP26(1)	NMRAL1(1)			QDPR(1)		MAG(1)	FRMD8(1)		BIN1(1)	TYRO3(1)	PLP1(1)	CDC42EP2(1)	KCTD13(1)	PRR18(1)		ASPA(1)			RTKN(1)			STMN4(1)			PIGZ(1)		TPRN(1)	NKAIN2(1)	ADAMTS4(1)		ARSG(1)		PLEKHH1(1)	EDIL3(1)	TSPAN2(1)			NKAIN1(1)	
 Precursor(1)   :0002453(1)		GPR17(1)			CNTN6(1)			LHFPL3(1)				GRIN3A(1)	OLFM2(1)			MMP16(1)								SEMA5B(1)	CHRNA4(1)		SHC4(1)	MEGF11(1)			GRIK3(1)	SLC35F1(1)				SLC7A3(1)			NEU4(1)		GNG3(1)		TNR(1)			LRRTM3(1)					RPRM(1)	OPCML(1)			ADAM12(1)	FZD9(1)	C1QL2(1)	TRAF4(1)						CHST5(1)						FAM89A(1)			ELFN2(1)	ELFN1(1)	RLBP1(1)	ACAN(1)	SOX3(1)				
     :				FOXD1(1)			ABCC6(1)		SEBOX(1)	PLXDC1(1)	HIC1(1)	BMP5(1)	SFRP2(1)		ATP13A5(1)						GYPC(1)		ATP1A4(1)			PTH1R(1)		HOXA13(1)			ARHGAP42(1)											SLC6A13(1)		SLC6A12(1)								NODAL(1)		NOX3(1)				PSCA(1)					PRR9(1)				ART3(1)							
Unknown(1)  			GABRA6(1)										KRT16(1)																							KIF5A(1)														SUSD3(1)					RPS29(1)												ARHGAP4(1)					RIMS1(1)"
test_phrase <- "ABC(1) ABCD(2) AB(4) A(1)"
```

```{r}
#https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=Tabula_Sapiens
#https://planetcalc.com/3205/
TabulaSapiens <- "Bladder-bladder(1) Urothelial(1) Cell(349)		GDF15(2)	RPS8(440)	RPL21(396)	RPS9(396)	RPS6(422)	RPS7(335)	SPINK1(10)	RPSA(184)	EEF1A1(451)	FAU(354)	S100A6(230)	RPL28(434)	RPL29(395)	RPL11(441)	RPL12(428)	RPL15(361)	SNCG(2)	RPS5(251)	RPL14(323)	RPS2(416)	RPS3(403)	RPL19(435)	B2M(412)	RPL18(401)	S100A11(87)	RPL41(457)	EIF1(368)	RPS27(450)	RPS29(346)	RPS28(435)	NACA(231)	LCN2(21)	RPS21(323)	ND2(391)	ND1(380)	RPS23(432)	FTL(389)	ND4(460)	ND3(459)	RPS24(437)	ND5(235)	RPL5(310)	RPL6(335)	RPL3(404)	RPL30(441)	RPL32(446)	ATP6(462)	RPL34(440)	ACTG1(226)	TACSTD2(14)	RPL9(383)	RPL8(407)	RPS16(375)	RPS15(424)	RPS18(446)	RPS19(431)	FTH1(409)	RPL37(431)	RPL36(383)	COX3(468)	RPL39(407)	COX2(469)	COX1(467)	RPS11(352)	RPS14(447)	RPS13(373)	RPL13A(390)	KRT13(8)	RPS3A(387)	PTMA(412)	KRT19(45)	KRT18(30)	KRT17(6)	RPL37A(426)	CYTB(462)	BTG2(28)	AREG(75)	RPS15A(392)	RPS27A(430)	H3-3B(256)	RPL35A(404)	RPL23A(247)	ND4L(58)	DHRS2(1)	CLDN4(30)	S100P(19)	GAPDH(188)	TPT1(467)	CSTB(15)	PSCA(4)	RPLP2(407)	RPLP1(453)	GSTP1(44)	ADIRF(55)	RPL10A(271)	RPS4X(406)	TMSB4X(375)	RPL18A(417)	RACK1(225)	RPL7A(409)	
Bladder-capillary(1) Endothelial(18) 		GSN(46)	CD74(114)						TM4SF1(31)		MYL6(131)	IFI27(30)	VIM(249)			SPARCL1(79)			CALM1(73)			ZFP36(122)									JUND(178)		HLA-A(144)	HLA-B(192)		HLA-E(83)														C11ORF96(49)							SRP14(18)					MT2A(121)									IGFBP7(76)		TMSB10(341)				JUN(171)			NFKBIA(124)				SOCS3(27)				FOS(231)		CLDN5(18)					YBX3(31)							
Bladder-endothelial(1)  Of(43) Lymphatic(8) Vessel(10)																TFPI(11)									S100A10(74)				GADD45B(36)							GNAS(24)																				GNG11(12)															CCL21(14)			LYVE1(6)	ATP5F1E(92)				TFF3(19)		TIMP1(55)						KLF4(5)		FABP5(21)	KLF6(56)		CD63(60)	CEBPD(74)					AKAP12(11)			
Bladder-fibroblast(1)			LUM(8)					COL1A2(15)		SFRP2(3)	MGP(69)					S100A4(114)				FBLN1(14)													IGFBP6(20)																									LGALS1(60)										APOD(23)	IER3(39)				PLA2G2A(18)													DCN(30)	SOD2(53)	FOSB(58)			C1R(13)					CST3(108)						
Bladder-macrophage(1)			CD163(21)						HSPA1A(90)				S100A9(72)	S100A8(57)	HSPA1B(29)														RPS20(181)											HSPH1(14)										GLUL(17)									CTSB(21)	SRGN(165)	HSP90AA1(218)	HSPA5(17)		LYZ(53)	IL1B(24)				HLA-DRA(76)		CXCL8(36)		HSPB1(36)	DNAJB1(28)		FCER1G(31)				G0S2(17)		PLAUR(15)	RNASE1(25)			UBA52(225)		C1QB(26)	C1QA(28)	HSP90AB1(123)			THBS1(24)	HSPD1(9)					CCL4(58)	HLA-DPA1(37)	CCL3(23)	
Bladder-mast(1) 															CD69(41)						LMNA(13)	HPGDS(1)	RPL36AL(11)																							RPS25(204)																UBB(33)										TPSAB1(16)			ANXA1(49)									BTG1(164)	TNFAIP3(38)				CLIC1(3)													
Bladder-myofibroblast(1) 		PDGFRA(2)							PNRC1(23)			SLPI(42)						IFITM3(94)			ZFP36L1(23)									EGR1(34)							CRYAB(21)													MT1X(41)													A2M(21)										NFKBIZ(13)				COL3A1(9)													CEBPB(25)										ADAMTS1(23)		
Bladder-nk(1) 										PPIA(15)		RPL26(291)							PFN1(62)																RPS26(99)			RPL27A(235)													RPL35(260)																							HSPA8(29)						HMGB1(25)				NPM1(15)	IL32(21)	GZMB(12)						RPLP0(197)										
Bladder-pericyte(1) 						TPM2(30)										MYL9(29)			TAGLN(34)			TPM1(34)	FLNA(11)								MYH11(21)				IGFBP5(33)	DSTN(27)																	MT1M(12)							RGS5(11)				CALD1(32)													ACTA2(27)										KLF2(52)													CCL2(17)		
Bladder-plasma(1) 							HSPE1(6)										HSP90B1(28)	ZFP36L2(102)										XBP1(17)	HLA-C(68)	CYBA(62)																								EEF1B2(97)														HSPA6(4)			TSC22D3(107)	SSR4(26)					MZB1(20)			JCHAIN(25)								IGLL5(13)		FKBP11(9)				DERL3(11)		HERPUD1(22)				SEC11C(19)		
Bladder-plasmacytoid(1) Dendritic(15) 													RPL27(95)												PTGDS(11)									GPR183(12)							EZR(10)											CREM(5)					SOX4(11)																	ARL4C(6)						SEC61B(9)				PPP1R14B(2)														CXCR4(94)				
Bladder-smooth(1) Muscle(21) 								DES(9)			PCP4(5)											SYNPO2(5)																	SMTN(1)																	LPP(7)		MYLK(5)	ACTG2(5)				CNN1(3)																							CSRP1(5)						PALLD(2)		SYNM(1)				ACTC1(4)				
Bladder-t(1) 																																															IL7R(68)																																																							
Bladder-vein(1)  																					CLU(52)																										ITM2B(71)																																												ACKR1(14)											
Blood-cd24(1) Neutrophil(4)		MMP8(3)			DEFA3(5)	DEFA4(1)	AZU1(2)							CEACAM8(2)	CEACAM6(4)					PABPC1(33)		MS4A3(1)			CD24(18)				IFITM2(33)			RETN(3)	MPO(3)	OAZ1(64)	SERF2(86)			CTSG(5)		S100A12(16)	ELANE(2)		ALOX5AP(18)			MYL12A(39)			MNDA(17)				BPI(1)	PRTN3(3)		LTF(11)			CD46(1)																			ARHGDIB(11)					TSPO(16)		H4C3(27)		PGLYRP1(3)				
Blood-cd4-positive(2), Alpha-Beta(42) T(57) 			RPL22(28)																																																RPL4(29)								RPL7(43)											RPS10(61)		RPL38(164)																	TXNIP(177)	LTB(3)												
Blood-cd8-positive(2),   																										NKG7(20)																																																										CD52(17)		GZMA(12)											GNLY(29)		CCL5(31)			
Blood-erythrocyte(1)		KRT1(2)	UBE2H(4)		SLC25A39(10)		ISCU(1)	FKBP8(7)	EIF1B(3)		SLC25A37(21)		YPEL3(5)	NFIX(3)	EPB41(6)	CCNI(3)	BSG(12)	MXI1(5)	PIP4K2A(2)		SNCA(10)	FIS1(3)	GABARAPL2(4)	MAP2K3(5)		BNIP3L(11)	SIAH2(1)	TALDO1(4)	TENT5C(4)	H1-2(3)		WNK1(3)	MKRN1(7)	BCL2L1(2)					BLVRB(10)	ANP32B(1)		C9ORF78(3)	GSPT1(5)	PRDX5(6)		BAG1(3)	PRDX2(13)					SEC62(6)	SKP1(2)	GPX1(41)	STRADB(4)	NCOA4(6)	HBA1(14)	RAD23A(8)	HBA2(25)		PDZK1IP1(3)	FAM210B(8)	CHPT1(1)	TRIM58(9)	HAGH(3)		TERF2IP(5)	R3HDM4(2)	FECH(4)	GYPC(10)	GMPR(4)	HBB(19)	SMIM1(1)	HBD(11)	ADIPOR1(5)		MAP1LC3B(2)	CA1(13)	STMP1(2)	HBQ1(2)		DMTN(1)	RBM38(8)	GLRX5(10)	BPGM(7)	SELENBP1(6)			RNF10(5)	ALAS2(10)	YBX1(33)		CCNDBP1(2)		GUK1(10)	ELOB(5)	MARCHF8(4)	FBXO7(6)	RIOK3(6)	DCAF12(6)	AHSP(11)	
Blood-hematopoietic(1) Stem(12) 																																														RPL31(44)																																																							HNRNPA1(7)	
Blood-memory(1) B(14) 																																																													CD79A(4)																																									
Blood-monocyte(1)							TYROBP(41)														COTL1(15)																																																									VCAN(13)				H3-3A(44)		CTSS(33)	SH3BGRL3(59)										AIF1(20)							
Blood-myeloid(1) Progenitor(4)																											EEF2(19)																																																								HINT1(2)																			
Blood-naive(2)  																																																																																		CD37(8)																				
Blood-nampt(1) 		SH3GLB1(1)	IL1R2(15)	GCA(12)					CLEC4E(1)							CSF3R(11)		STXBP2(2)	AQP9(5)	BASP1(14)			PROK2(3)			FYB1(12)						SDCBP(10)			ARPC3(5)	ARPC2(8)		CYSTM1(3)							GMFG(4)		SLC2A3(14)		EFHD2(2)		GYG1(1)				ANXA3(1)	C1ORF162(1)	RHOG(1)	MMP9(8)			PTPRC(33)	FCGR2A(4)	C4ORF3(1)	ALPL(2)	IDI1(1)	GPSM3(1)		SERPINA1(17)	BCL2A1(9)	FPR1(11)	IQGAP1(6)	LITAF(10)								CDKN2D(1)	SERPINB1(5)			UBALD2(1)			FOLR3(1)					PYGL(4)	CST7(12)	LILRA5(1)		NAMPT(19)			
Blood-nk(1) 										KLRD1(11)																										H1-4(4)																	DDX5(58)																																																	
Blood-plasmablast(1)									SUB1(9)						PPIB(9)																																																																	CALR(5)																						
Lung-adventitial(1) 										CCDC80(9)												ITLN1(9)																																		C3(14)																	SFTPC(8)										NNMT(12)																			
Lung-alveolar(1) Fibroblast(1)																			ADH1B(15)										CCN2(6)										SERPING1(16)																																						GPX3(25)							TIMP3(61)																		
Lung-b(1) 										SCGB1A1(10)																																																																																												
Lung-basal(1) 			S100A2(12)								CD9(21)																																															WFDC2(28)																											SERPINB3(6)																	
Lung-basophil(1)																																																						LGALS3(34)							APOE(34)																					CTSD(13)					APOC1(6)	PLIN2(5)														
Lung-bronchial(2) Smooth(5)  										SELENOM(3)								CALM2(20)									CCN5(4)																																																	CAV1(23)											PPP1R14A(8)	NDUFA4(14)														
Lung-capillary(2) Aerocyte(1)			CAVIN2(11)	ARHGAP29(2)				EMCN(2)				LY6E(2)					MT1E(25)		APP(5)		EPAS1(16)			HPGD(4)	PON2(1)		MYL12B(8)	SLC9A3R2(11)		STOM(7)														RGCC(10)	ADGRF5(3)							FCN3(8)	SPARC(11)									PODXL(1)							EGFL7(2)			EMP2(2)	RHOB(21)		ID1(17)	ID3(10)	PECAM1(12)		SGK1(4)	RTN4(4)			CA4(2)				IFNGR1(2)				RAMP2(3)						IL1RL1(7)		EDNRB(3)	HYAL2(2)	CD59(13)	
  																																																	CALCRL(1)									FAM107A(2)		SLC6A4(1)					IER2(36)															LRRC32(1)						VWF(17)			F8(2)										THBD(3)			
Lung-cd4-positive(2),   																																																																																																						
Lung-cd8-positive(2),   																																																																																																						
Lung-classical(1) Monocyte(10)																																																																																										PFDN5(13)												
Lung-club(1) 																												HOPX(4)																										MGST1(11)																	SFTPB(5)				CYB5A(7)			SCGB3A1(15)	SCGB3A2(3)												PIGR(31)											
Lung-dendritic(1) 																																																																																							S100B(6)											TUBA1B(22)				
Lung-endothelial(2)   Artery(5)																																																																																																						
    																																																																											ANXA2(30)					MMRN1(8)																						
Lung-lung(2) Ciliated(1) 									GSTA2(1)	GSTA1(4)								HOATZ(1)			CIB1(2)	ATP5IF1(3)					HMGN3(1)			IGFBP2(6)		TMEM190(2)			BPIFB1(9)																																TSPAN1(6)											ELF3(27)	TPPP3(3)					C20ORF85(2)				DYNLL1(4)	CYP4B1(2)	C9ORF24(2)	TUBB4B(4)	ALDH1A1(2)	RSPH1(2)					TUBA1A(7)		AGR3(2)		
 Microvascular(1)  																																																																																																						
Lung-macrophage(1)																	CD81(9)																																																FN1(6)				FBP1(1)				ACP5(2)								CHIT1(2)	FABP4(20)										GRN(2)								CCL18(2)		
Lung-mesothelial(1) 		RARRES1(16)						KRT8(33)																																																																																														
Lung-myofibroblast(1) 													MT1G(12)																																					GPM6B(2)																																										PLP1(5)											
Lung-nk(1) 																																																																							FGFBP2(2)																														
Lung-non-classical(1) 																																																																																																						
Lung-pericyte(1) 		PDGFRB(3)																					DPYSL2(2)									NR2F2(4)																					HIGD1B(1)				GJA4(1)														INMT(1)							KCNK3(1)	COX4I2(1)							BGN(3)		COL4A1(5)	COL4A2(4)	NDUFA4L2(3)		RGN(1)		ITGB1(6)								
Lung-plasma(1) 																															ISG20(3)																																														H1-10(8)								SPCS2(4)	SPCS1(4)		SFTPA1(3)	SFTPA2(3)													
Lung-plasmacytoid(1)  																																									ITM2C(4)																																		IRF8(2)	IRF7(1)				CLIC3(1)																				CCDC50(1)		
Lung-respiratory(2) Goblet(4) 							KRT7(17)													CXCL17(8)																																								BPIFA1(5)																																							AGR2(14)		MSMB(3)	
Lung-serous(1)   Epithelium(11)  Bronchus(1)							SLC12A2(1)			AZGP1(15)						AQP5(6)	STATH(15)	NDRG2(1)										MUC7(4)									TCN1(2)												CRISP3(2)																				FDCSP(4)											ZG16B(11)		C6ORF58(3)					ODAM(1)											PRB4(13)	DMBT1(3)	PRB3(14)		
Lung-type(2) I(4) Pneumocyte(2)						APLP2(4)													MUC1(3)	RAB11FIP1(7)								NAPSA(2)			PGC(6)																					AGER(1)																						GPRC5A(1)			NPC2(9)																								CD55(14)	
 Ii(1) 																										SLC34A2(2)																																																						CXCL2(16)										SFTA2(1)												
Lung-vascular(1) Associated(4)   																																																																														ECRG4(1)																							
Lung-vein(1)  								LIFR(2)																																																																																									PRSS23(3)					
Muscle-capillary(1)  								MT1A(6)																																																														EMP1(11)											CD36(8)				DNAJA1(15)			HNRNPA2B1(18)			FLT1(6)			CDKN1A(8)								
Muscle-cd4-positive(1),   																																																																																																						
Muscle-cd8-positive(1),   																																																																																																						
Muscle-endothelial(3)   																																IGFBP3(4)																																																											KCTD12(2)											
    																																																																																																						
   Vascular(1) Tree(1)																													SELE(7)																																													IL6(3)			STC1(4)																							ADAMTS9(1)		
Muscle-erythrocyte(1)					RBX1(3)										EPB42(3)																ND6(9)																										PA2G4(1)								TOP1(7)			GYPB(5)						SPTA1(4)	CA2(9)											HEMGN(8)					SLC4A1(8)									
Muscle-fast(1)  		GAMT(2)		CKM(4)	ACTN2(2)		EEF1A2(2)		MYL1(5)	MYL2(2)		SELENOW(5)				COX6A2(4)	SLN(2)			MYL11(4)				TNNC2(4)					TNNT3(3)	BIN1(2)									UQCRB(7)					COX7A1(4)	ENO3(3)						CMYA5(3)						PPDPFL(2)							NEB(3)			ATP5F1D(3)	MYBPC1(3)	MYH2(2)	ACTA1(3)		TOMM7(4)	SLC25A4(4)	COX7C(14)		LDHA(9)	PDLIM3(2)	MB(4)	CA3(2)	ANKRD1(2)		PDLIM5(2)			PGAM2(2)		KLHL41(3)	PKM(4)		TCAP(5)						PYGM(2)	ATP2A1(1)		TNNI2(3)		MYOZ1(2)	
Muscle-macrophage(1)					EREG(16)	SELENOP(12)																																	INSIG1(2)																						CCL20(6)														CXCL3(11)											CD44(4)							F13A1(6)							MRC1(7)		
Muscle-mast(1) 																																						BIRC3(4)																	RGS2(21)																																			DDIT4(12)											
Muscle-mature(1) Nk(8)  																																																																																HCST(3)																						
Muscle-mesenchymal(1)  																																			COL6A3(5)																																																																			
Muscle-pericyte(1) 															ATF3(14)																																																																																				ADAMTS4(2)			
Muscle-skeletal(1)  Satellite(1)  																																																																																																						
Muscle-slow(1)  						TPM3(7)	S100A1(1)							MYL3(2)																	TNNT1(1)																				MYL6B(1)																							MYH7(1)				CSRP3(1)				ANKRD2(1)		STRIT1(1)																TNNI1(3)		
Muscle-t(1) 																									CNOT6L(1)																																																																										SMCHD1(4)			
Muscle-tendon(1) 								COL1A1(8)												COMP(1)																	COL6A1(3)																																																MYOC(3)											PRELP(4)	THBS4(1)				
Pancreas-b(1) 																																																																																																						
Pancreas-endothelial(1) 																			PLVAP(4)			GIMAP7(1)								IGFBP4(7)																															SOX18(1)															TGFBR2(3)																		ENG(2)								
Pancreas-mast(1) 																	PPP1R15A(10)																																							SAMSN1(7)					RGS1(20)																																										
Pancreas-myeloid(1) 																																																																																																						
Pancreas-pancreatic(7) Acinar(1) 											PRSS2(5)								PRSS3(2)		CELA2A(2)	CPA2(2)	CELA2B(2)	CPA1(2)		CEL(4)					CLPS(5)	SYCN(2)									PNLIP(2)		CELA3A(2)	REG1A(11)	CELA3B(1)				AMY2A(1)	CPB1(2)	AMY2B(1)					REG1B(1)																			GP2(3)		CTRL(1)			CTRC(2)	PNLIPRP2(2)	PNLIPRP1(2)	KLK1(1)			CTRB2(2)			GATM(1)	CTRB1(2)	P4HB(1)			PLA2G1B(2)								
 Alpha(1) 		CHGB(5)	CHGA(6)						TM4SF4(2)	GCG(4)			SPINT2(1)		SCG5(6)													SLC30A8(1)																																							PCSK1N(6)									CPE(7)		PCSK2(1)									ERO1B(5)				CRYBA2(2)		INS(4)	TTR(8)					GC(2)			
 Beta(1) 												SST(4)	IAPP(2)								PEBP1(10)																																																																																	
 Delta(1) 																																																																																																						
 Ductal(1) 									ATP1B1(9)																																	CFTR(2)																																	ANXA4(2)																					SLC4A4(1)						
 Pp(1) 															AKAP9(2)		AQP3(6)								PNISR(1)																																PPY(1)									ZKSCAN1(1)						MEIS2(1)					LUC7L3(2)						DST(8)				CIRBP(1)	GHRL(3)															
 Stellate(1) 																						SERPINF1(6)																																																																																
Pancreas-t(1) 								CD2(2)																																																																																														
Bladder-b(1) 																																																																																																						
Blood-granulocyte(1)																																																																																			SNX3(3)			HLA-DQA1(6)																	
Blood-macrophage(1)																																																																																																						
Blood-plasma(1) 																																																																																																						
Bone(16) Marrow-cd24(1) 		CSGALNACT2(1)						OLFM4(9)								FCN1(3)	CD177(5)										ARPC5(4)	CYBB(2)						CKAP4(1)			PADI4(3)	PLBD1(1)																	ACTR3(2)	ACTR2(4)											MYH9(2)	MEGF9(3)				ABHD5(3)			HMGB2(11)			IRAK3(5)	EMB(1)	LBR(1)	MCL1(11)				YWHAZ(4)								LSP1(4)	SYNE1(5)		SYNE2(6)						
 Marrow-cd4-positive(1),   																																																																																																						
 Marrow-cd8-positive(1),   																																																																										DUSP2(15)																												
 Marrow-erythroid(1) 																																																																																																						
 Marrow-granulocyte(1)																																																																																																						
 Marrow-hematopoietic(1)  																																																																																																						
 Marrow-macrophage(1)																																																																																																						
 Marrow-memory(1)  																																																																																																						
 Marrow-monocyte(1)																																																																																																						
 Marrow-myeloid(1) 																																																																																																						
 Marrow-naive(1)  																									HLA-DRB5(3)																																																		EEF1D(19)				MS4A1(2)							LAPTM5(14)																
 Marrow-nk(1) 																																																																																																						
 Marrow-plasma(1) 																KRTCAP2(1)																																		PRDX4(3)					TXNDC5(5)												SSR3(5)				TMBIM6(5)			LOC102724971(1)										TMEM59(4)																		
Kidney-b(1) 																																																																																																						
Kidney-cd4-positive(1) Helper(5)  																																																																																																						
Kidney-cd8-positive(1),   																																																																																																						
Kidney-endothelial(1) 					SLC12A1(1)											IL6ST(4)						AHNAK(9)			DEFB1(8)		CRHBP(2)		KDR(1)																				PLPP3(3)				PLPP1(3)									PLAT(1)			PDK4(22)												PTPRB(1)				SEC14L1(1)			SPTBN1(2)			DDX17(4)															
Kidney-kidney(1) Epithelial(8) 																																																		ATP5MC3(3)							PRDX1(6)																			ALDOB(4)			COX7B(4)		LDHB(2)		COX4I1(16)	ATP5MK(1)		PCK1(5)					SLC25A5(1)			C11ORF54(1)								
Kidney-macrophage(1)																																																																																																						
Kidney-nk(1) 																																																		ETS1(1)																				ATM(1)		CD247(1)																														
Large(24) Intestine-b(2) 																																																																															EMP3(2)																							
 Intestine-cd8-positive(2),   																																																																																																						
 Intestine-fibroblast(2)																																																																																																						
 Intestine-goblet(2) 									ZG16(3)								CLDN3(15)		MUC2(4)								PHGR1(20)																								LGALS4(16)										CLCA1(4)																		EPCAM(10)																	FCGBP(6)						
 Intestine-gut(2)  																																																																																																						
 Intestine-immature(2) Enterocyte(4)																																																													TSPAN8(10)																				C15ORF48(11)									FABP1(10)												
 Intestine-intestinal(8) Crypt(4)  																																																																																																						
  Enteroendocrine(2) 																																																			SCGN(1)			LCN15(2)																					COX6C(6)		PYY(2)						TPH1(1)									VMP1(7)									INSL5(1)	
 Intestine-mature(2) 		ACTN4(1)						SCNN1B(3)																	CDHR5(2)								SLC26A3(2)		SLC26A2(1)	ATP8(8)									MUC13(1)							CLCA4(1)	MUC12(2)			TSC22D1(8)				CEACAM1(1)			CEACAM7(1)	FXYD3(3)	CEACAM5(2)					ATP5ME(5)	KRT20(3)													UGT2B17(1)				GUCA2A(2)	CLDN7(1)			PPDPF(13)						COX5B(10)				
 Intestine-paneth(2)      Intestine(10)																	BEST4(1)							PHLDA2(3)																																																													CA7(1)					GUCA2B(1)												
 Intestine-transit(2) Amplifying(2)    																																																																																																						
Lung-fibroblast(1)																																																																																																			DEPP1(5)			
Lung-intermediate(1) 																																																																																																						
Lung-neutrophil(1)				ACSL1(8)									IVNS1ABP(5)				RIPOR2(8)									NIBAN1(6)									MXD1(8)									IL1RN(4)					ETS2(2)													RNF149(7)					IGSF6(1)											PDE4B(1)									SORL1(6)									PLEK(7)						
Lung-pulmonary(1) Ionocyte(1)					RARRES2(4)																	ASCL3(2)							POSTN(2)	ATP6V0B(3)				IGF1(4)																					ARHGAP18(1)			COX7A2(2)																															TMEM61(1)											CHCHD2(4)		
Lymph(29) Node-cd141-positive(1) Myeloid(7)  																																									HLA-DRB1(15)																																																													
 Node-cd1c-positive(1)   																FGL2(3)																																																																																						
 Node-cd4-positive(2),  Memory(7)  																																																																																																						
 Node-cd8-positive(2),    																																																																																																						
 Node-classical(1) 																																								C5AR1(9)																																																														
 Node-endothelial(1) 																																																																																																						
 Node-innate(1) Lymphoid(3) 																																																																																																						
 Node-intermediate(1) 																																																																																																						
 Node-macrophage(1)														SQSTM1(5)																																																		ANXA5(5)							CPM(1)	CTSZ(2)			PLD3(1)	CTSK(1)														C1QC(14)										GPNMB(1)		
 Node-mast(1) 																																																																																MS4A2(2)																						
 Node-mature(2)   																																																																																																						
 Node-memory(1)  																																																																																																						
 Node-naive(2)  																																																																																																						
  Thymus-Derived(6) Cd4-Positive(4),   																																																																																																						
 Node-nk(1) 																																																																																																						
 Node-plasma(1) 		H2AZ1(5)																											PDIA6(1)																				UQCRH(3)			MYDGF(2)																											MTDH(1)																							
 Node-regulatory(1)  																																																																																																						
Small(25)  																																																																																																						
 ,   																																																																																																						
 Intestine-duodenum(1) Glandular(1) 							GOLM1(2)															MUC6(1)																																LIPF(1)																								TFF2(2)											NUCB2(1)													
 																ADAMDEC1(1)			CXCL14(6)																																																																																			
  				DEFA5(3)																			HES6(1)																																REG4(2)																							REG3A(4)		MDK(4)														CDKN1C(1)								
   																																																																																																						
  																																																																																						AKR1C3(2)																
    																																																																																																						
   																																																				NTS(2)																																													DIRAS3(1)			GAST(1)		
  Tuft(2) 		TLE4(1)					IRAG2(1)	MATK(1)																													CCSER1(1)																	KMT2C(1)														PLCG2(1)					SH2D6(2)	ARGLU1(4)		TRPM5(2)										ITPR2(2)	PSTPIP2(2)				MARCKSL1(2)											
  				DEFA6(2)		TMPRSS15(1)	SRRM2(1)					MT1H(1)											SLC5A1(1)		SLC15A1(1)																			GOLGA4(1)					ANPEP(1)										APOB(5)				APOA4(2)						APOA1(4)					CYP3A4(2)	CYP3A5(3)					CBR1(1)				PTGR1(1)	FABP2(1)					APOC3(3)	SMIM24(1)						SLC20A1(3)				SLC4A7(1)	
       																																																																																	TFF1(2)																					
      																																																																																																						
Spleen-cd141-positive(1)   																																																																																																						
Spleen-cd1c-positive(1)   															CPVL(3)																																																														ID2(6)																									
Spleen-cd4-positive(1),    																																																																																																						
Spleen-cd8-positive(2),    																																																																																																						
,   																																																												STMN1(3)																																									
Spleen-classical(1) 																																																																																																						
Spleen-endothelial(1) 				TPM4(7)		KAZN(1)															INSR(2)				PLK2(1)									CDH11(1)																		PCDH17(1)										ITGA1(1)																			LIMCH1(1)							PEAK1(1)		DNASE1L3(2)			SEMA3D(1)									
Spleen-erythrocyte(1)										HMBS(5)																																				TFRC(5)																																																								
Spleen-innate(1)  																																																																																CITED2(1)																						
Spleen-macrophage(1)									VCAM1(1)																																		CCL4L2(5)									HMOX1(4)																									SLC40A1(1)															CD5L(1)										
Spleen-mature(1)   																																																																																																						
Spleen-memory(1)  																																																																																																						
Spleen-naive(3)  																																																																																																						
  ,   																																																																																																						
  Cd8-Positive(2),   																																																																																																						
Spleen-neutrophil(1)																					IFITM1(4)																			VNN2(6)							SPI1(2)																																																		PTGS2(4)					
Spleen-nk(1) 																																																																																																						
Spleen-plasma(1) 																																																																																																						
Spleen-plasmacytoid(1)  																																																																																																						
Spleen-regulatory(1)  																																																																																																						
Thymus-capillary(1)  			BTNL9(1)						RBP7(1)																																																																																													
Thymus-cd4-positive(1)   																																																																																		SARAF(17)																				
Thymus-cd8-positive(2),   																																																																																																						
Thymus-dendritic(1) 																																																																																																						
Thymus-endothelial(2)   																																																																																																						
    																																																											EFEMP1(4)																																											
Thymus-erythrocyte(1)				EIF1AY(5)						TMCC2(2)	CPEB4(3)						FOXO3(2)												EIF5(2)								SLC2A1(2)			UROD(2)																				ARL4A(2)											ANKRD9(1)							KLF1(1)		KLF3(1)	SOD1(3)			RHAG(3)								TRAK2(2)	NUDT4(3)		XPO7(2)				FBXO9(3)			
Thymus-fast(1)  										FKBP5(3)																																																											TRDN(2)																																	
Thymus-fibroblast(1)																																		COL6A2(12)																					NR4A1(10)																																															
Thymus-immature(1) Natural(1) Killer(1) 																																																																																																						
Thymus-macrophage(1)																																																																								PLTP(3)	CTSL(6)																										FCGRT(2)			
Thymus-mast(1) 																																																																																											KIT(1)											
Thymus-mature(1)   																																																																																																						
Thymus-medullary(1) Thymic(2)  																																																																																																						
Thymus-memory(1)  																																																																																																						
Thymus-mesothelial(1) 																						TCEAL4(2)											UPK3B(1)																																																OGN(2)											MSLN(1)										
Thymus-monocyte(1)																																																																																																						
Thymus-naive(2)  																																																																																																						
Thymus-nk(1) 																																																																																																						
Thymus-plasma(1) 																																																																																																						
Thymus-thymocyte(1)																									NDFIP1(1)										ITM2A(1)																																											CD3E(1)	CD3D(1)																					JAK1(1)		
Thymus-vascular(1)    																																																																																																						
Thymus-vein(1)  																																																																																																						
Trachea-basal(1) 		KRT5(9)																		KRT6A(4)																																																									KRT14(9)						KRT15(3)																			
Trachea-ciliated(1) 						DNAAF1(1)										ODF3B(1)										OMG(1)																													PIERCE1(1)	PSENEN(1)				PIFO(1)	GPX4(4)			TMC5(1)							UFC1(1)						CETN2(1)					NQO1(2)						MORN2(2)	FAM183A(1)	SMIM22(1)									CFAP276(1)			
Trachea-connective(1) Tissue(2) 																																												FBN1(2)																															MMP2(4)				MFAP5(4)																C1S(8)							
Trachea-endothelial(1) 																																																																																										FKBP1A(2)												
Trachea-goblet(1) 																																																																													CP(5)										MUC5B(6)															
Trachea-macrophage(1)																																																																																																						
Trachea-plasma(1) 																																																																																																						
Trachea-secretory(1) 																																																																																		CXCL1(7)																				
Vasculature-b(1) 																																																																																																						
Vasculature-endothelial(1) 																																																																																																						
Vasculature-epithelial(1) 																																																																																																						
Vasculature-erythrocyte(1)																																																																																																						
Vasculature-fibroblast(1)																																																																																																						
Vasculature-macrophage(1)																																																																																																					VSIG4(2)	
Vasculature-mast(1) 																																																																																																						
Vasculature-nk(1) 																																																																												XCL2(1)																									
Vasculature-pericyte(1) 																																																																																		LMOD1(3)						MAP1B(7)			STEAP4(4)											
Vasculature-plasma(1) 							IGL(1)																																																																																															
Vasculature-smooth(1)  																																									MFGE8(4)																																																													
Vasculature-t(1) 																																																																																																						
Eye-cd4-positive(1),   																SRSF7(3)				SERPINE2(2)									JAG1(1)								LCN1(10)																																																	PMEL(3)								TYRP1(3)									
Eye-conjunctival(1)  							KRT4(2)																		PERP(6)												ALDH3A1(4)																																																		KLF5(2)															
Eye-corneal(2) Keratocyte(1)																																																																																																						
Eye-limbal(2)  																																																					ENO1(5)																						KRT12(3)																											
 Stromal(1) 						TFPI2(1)	OPTC(1)													FRZB(3)																																																																				F5(1)	DCT(2)							DAPL1(1)						
Eye-monocyte(1)																																																																																																						
Eye-retinal(4) Blood(1)   																																																																																										SPRY1(2)												
Mammary-b(1) 																																																																																																						
Mammary-basal(1) 																																	FBXO32(1)																																																																					
Mammary-endothelial(2)   																					SERPINE1(7)																																																																																	
    																		RGS16(2)																																			PPFIBP1(1)																			ANGPT2(1)																														
Mammary-fibroblast(1)  Breast(1)																																																																				MMP3(3)							TNFAIP6(2)																				THBS2(1)							
Mammary-luminal(1)    Mammary(1) Gland(4)																																																																																																						
Mammary-macrophage(1)																																																																																																						
Mammary-mast(1) 											MELTF(1)						ASAH1(3)																									SYAP1(2)																													TPI1(3)								HILPDA(1)																						
Mammary-nk(1) 									SYTL3(1)		CD7(4)																																																																																										FYN(1)		
Mammary-pericyte(1) 																																																																																																						
Mammary-plasma(1) 							ERN1(1)									SELENOK(2)																																																									P4HA1(1)				SLC3A2(1)																					SERP1(1)				
Mammary-t(1) 																																																																																																						
Mammary-vascular(1)    																																																																																																						
Mammary-vein(1)  																																																																																																					
Uterus-b(1) 																																																																																																							
Uterus-ciliated(1)  																																																																																										SCGB2A1(4)												
Uterus-endothelial(2) 																	CSF3(1)				NDRG1(1)																																	ICAM1(2)																																																
    																																			ISG15(1)																																																																			
Uterus-epithelial(2) 																																																																					MMP7(3)																																	
   Uterus(1)																																																																																																						
Uterus-fibroblast(1)									SFRP4(1)																																																																	MMP11(1)																												
Uterus-immune(1) 																																																																																																						
Uterus-macrophage(1)																																																																				CCL3L1(2)												SERPINB2(2)																						
Uterus-myometrial(1) 																																																																																																						
Uterus-nk(1) 																																																																																CTSW(1)																						
Uterus-pericyte(1) 																																																																																																						
Uterus-t(1) 																																																																																																						
Uterus-vascular(1)    																																																																																																						
Eye-b(1) 																																																																																																						
Eye-cd8-positive(1),   																																																																										CCL23(1)																														
Eye-ciliary(1) Body(1)				DIO2(1)												CHRM3(1)					HNRNPU(3)	PRUNE2(1)																																															PPP1R12A(1)	PPP1R12B(1)														CSRP2(3)					SORBS2(1)		PLCB4(1)							ATP2A2(1)			
  						KRT3(1)			TGFBI(1)										CLDN1(1)															SDC1(1)																	LYPD3(2)																								DSG1(1)																								RND3(2)			
Eye-dendritic(1) 																																																																																																						
Eye-endothelial(1) 																																																																																																						
Eye-epithelial(1)   Lacrimal(1) Sac(1)										OPRPN(2)																																															SMR3A(1)															FGFBP1(2)																														
Eye-erythroid(1) Lineage(1) 			LACRT(2)																																																																																																			
Eye-eye(1) Photoreceptor(1) 												AIPL1(3)		PLEKHB1(1)	NRL(3)	LAPTM4B(1)			GNAT1(3)		HMGN1(2)	RTBDN(1)		CLUL1(1)					GNB1(2)	UNC119(2)	VAMP2(3)								CNGB1(1)								NTM(1)	ENO2(2)					RIMS2(1)	KCNV2(1)			EPB41L2(1)												ROM1(3)			ARL4D(1)					GNGT1(3)				CNGA1(1)	RCVRN(3)																	RHO(3)	PDE6A(2)		
Eye-fibroblast(1)						KERA(1)				ITGBL1(1)											COL12A1(1)																											CFH(3)																																												ANGPTL7(1)										
Eye-lacrimal(1)  Functional(1) Unit(1) 																			SFRP1(1)																																									SCGB1D1(1)						PRR27(3)																												HTN1(14)	CST4(1)				CST1(1)			
Eye-macrophage(1)														CD83(5)											MAFB(1)			MAF(1)																																																				MAN1A1(1)																						
Eye-mast(1) 																															NR4A2(2)																																																										ADCYAP1(2)											
Eye-melanocyte(1)							MITF(1)																																																																										MLANA(1)																					
Eye-microglial(1) 																																																																																																						
Eye-muller(1) 							PPA1(1)									CRABP1(3)					WIF1(1)																																																																							FABP7(1)						RLBP1(2)				
Eye-ocular(1) Surface(1) 																																																																																																						
Eye-plasma(1) 																																																																																																						
Eye-radial(1) Glial(1) 																																																																																																						
Eye-retina(1) Horizontal(1) 																																																																																	CNTNAP2(1)								SEPTIN7(2)						PTMS(2)							
 Bipolar(1) Neuron(1)																	ATP1A3(1)								SYT1(1)																	BEX3(1)					RORB(1)																				PAX6(1)		GNG13(1)				ZEB2(1)					SNAP25(1)		YWHAB(1)											MGARP(1)	VDAC1(1)				NUCKS1(1)				
 Pigment(1)  																BEST1(1)						COX8A(1)		CHCHD10(1)	TMA7(1)	RPE65(1)																				TMEM98(1)		TRPM3(1)									LRAT(1)																NDUFB2(1)	FHIT(1)	RDH10(1)					ATP5MG(1)					RGR(1)													ENPP2(1)	ITGB8(1)	ITGAV(1)	POLR2L(1)	
Eye-t(1) 																																																																																																						
Liver-endothelial(2)   Hepatic(1) Sinusoid(1)																																																																													ALB(8)																									
Liver-fibroblast(1)																																																																																																						
Liver-hepatocyte(1)							ASS1(1)						FGL1(2)					SULT2A1(1)						HPD(1)	HAMP(1)														HPX(1)	VTN(1)			C5(1)		TDO2(1)				APOH(1)								AMBP(3)			APOA2(1)											ECHS1(1)		KNG1(1)		FGA(5)	FGB(6)	FGG(4)	DCXR(1)			BAAT(1)		MAT1A(1)		ANG(1)	CYP2E1(1)		AGXT(1)			APCS(1)	ORM2(1)		ORM1(2)	SERPINC1(1)			PLG(1)				
Liver-intrahepatic(1) Cholangiocyte(1)																																																																				GPX2(2)														CITED4(1)																				
Liver-liver(1)  																																																																																																					
Liver-macrophage(1)																																																																																																						
Liver-monocyte(1)																																																																																																						
Liver-neutrophil(1)																																																			GATA2(2)																				IL13(1)																																
Liver-nk(1) 																																																																								XCL1(1)																														
Liver-plasma(1) 																																																																																																							
Liver-t(1) 																																																																																																						
Trachea-b(1) 																																																																																																						
Trachea-cd4-positive(1),   																																																																																																					
Trachea-cd8-positive(1),   																																																																																																						
Trachea-double-positive(1),  Thymocyte(3)																																																																																																						
Trachea-fibroblast(1)																																																																																																						
Trachea-ionocyte(1)													SCD(2)																																																																																										
Trachea-mast(1) 																																																																																																						
Trachea-mucus(1) Secreting(2) 															ANKRD36C(2)																																																																																		VMO1(2)					
Trachea-neutrophil(1)									MARCKS(4)																																																												ADM(1)																						ITGB2(1)											
Trachea-serous(1)     Trachea(1)																																																																																																						
Trachea-smooth(1)  																																																																																																				CCL19(1)		
Trachea-t(1) 																																																																																																						
Trachea-tracheal(1)  																																													LYPD2(1)																								MUC5AC(1)																																	
Blood-basophil(1)																																																																																																						
Blood-cd141-positive(1)   																																																																																																					
,    																																																																																																						
,  Cytokine(1)  Effector(1)  																																																																																																						
Blood-classical(1) 																																																																																																						
  ,   																																																																																																						
Blood-neutrophil(1)																														SLC11A1(2)													SELL(3)	TAGLN2(3)								ANP32A(3)										CFLAR(5)																							EVI2B(4)											VSIR(1)						
Blood-non-classical(1) 																																																																																																					
Blood-plasmacytoid(1)  																																																																																																						
Blood-platelet(1)							TUBA4A(2)			RUFY1(1)			PF4(2)	TLN1(2)	CALM3(1)				RGS18(2)	ITGA2B(1)									OST4(1)	H2AC6(2)	PPBP(2)						TREML1(1)			KIF2A(1)										VCL(2)					ACRBP(1)					PRKAR2B(2)								CMTM5(1)		NAP1L1(1)		GP9(1)			LIMS1(2)					RAP1B(2)						YWHAH(2)	PTCRA(1)		RGS10(1)							NRGN(2)						
Blood-t(1) 																																																																																																						
Blood-type(1)    																																																																																																						
 Node-b(1) 																																																																																																						
    																																																																																																						
    																																																																																																						
 Node-erythrocyte(1)																																																																																																					
 Node-hematopoietic(1)  																																																																																																						
  Conventional(1)  																													GADD45A(3)						FSCN1(1)																																									CENPF(1)							TOP2A(1)																		CCL17(3)	
 Node-neutrophil(1)																																																																																																	CXCR2(2)				
 Node-non-classical(1) 																			ZFAND5(1)																																																																																				
 Node-plasmacytoid(1)  																																																																																																						
 Node-stromal(1) 																																																																																																						
 Node-t(1) 																																																																																																						
 Node-type(1)    																																																																																																						
Salivary(23) Gland-acinar(1)    																																																								BPIFA2(2)	SMR3B(7)																							PRH1(5)	CA6(5)															HTN3(18)						
 Gland-adventitial(1) 																																																																															CILP(1)																							
 Gland-b(1) 																																																																																																						
 Gland-basal(1) 																																																																																																						
 Gland-cd4-positive(1)   																																																																																																						
 Gland-cd8-positive(1),   																																																																																																						
 Gland-duct(1)  																																																																																																						
 Gland-endothelial(2) 																																																																																																						
     																																																																																																						
 Gland-fibroblast(1)																																																																																																						
 Gland-memory(1)  																																																																																																						
 Gland-monocyte(1)																																																																																																						
 Gland-myoepithelial(1) 																																																																																																						
 Gland-naive(1)  																																																																																																						
 Gland-neutrophil(1)																																																																																																						
 Gland-nk(1) 																																																																																																						
 Gland-pericyte(1) 																																																																																																						
 Gland-plasma(1) 																																																																																																						
 Gland-t(1) 																																																																																																						
Spleen-hematopoietic(1)  																																																																																																						
Spleen-intermediate(1) 																										CPNE3(1)				HMGN2(1)																																																																								
Spleen-platelet(1)																																																																																																						
Spleen-type(1)    																																		PIK3R1(1)																																																																				
Tongue-basal(1) 		SPINK5(2)	KRTDAP(2)							S100A7(2)	LY6D(3)					RHCG(2)	SPRR3(3)				SBSN(2)								KRT6B(3)									SPRR1B(2)																		PI3(1)																	CNFN(2)	CRNN(2)			KRT16(3)	DSG3(1)			SPRR2A(3)			SPRR2D(1)	SPRR2E(2)								CSTA(3)									
Tongue-capillary(1)  																																																																																																						
Tongue-endothelial(2)   																																																																																																					
    																																																																																																						
Tongue-epithelial(1) 																																																																																							LGALS7B(2)															
Tongue-fibroblast(1)																																																																																																						
Tongue-immune(1) 																																																																																																						
Tongue-keratinocyte(1)				GBP6(1)																		CALML3(1)				S100A14(1)		PITX1(2)																																																								SLURP1(1)					IVL(1)					CRCT1(1)								
Tongue-pericyte(1) 																																																																																																						
Tongue-tongue(1)  																																																																																																						
Tongue-vein(1)  																																																																																																						
Prostate-basal(1)   Prostate(5) 																															CYP4F8(2)																																																											SEMG1(7)		SEMG2(5)										
Prostate-cd8-positive(1),   																																																																																																						
Prostate-cd8b-positive(1)   																																																																																																						
Prostate-endothelial(1) 																																																																																																						
Prostate-epithelial(1) 								NUPR1(2)		FDX1(1)												LAPTM4A(1)																																																		GSTM3(2)																		PRPS2(2)				AKR1B1(2)								
Prostate-erythroid(1) 																																																																																																						
Prostate-fibroblast(1)																																																																																														PTN(1)								
Prostate-hillock-club(1)    																																																																																																						
Prostate-luminal(1)    									FOLH1(1)			STEAP2(1)																																											PMEPA1(2)		NKX3-1(1)														H2AJ(1)				KLK2(1)	RDH11(1)		ACP3(1)						DHRS7(1)												NPY(1)		NEFH(1)				
Prostate-macrophage(1)																																																																																																						
Prostate-nkt(1) 																																																																																																						
Prostate-smooth(1)  																																																																																																						
Pancreas-fibroblast(1)											CRISPLD2(1)																EGR3(1)				NR2F1(1)																				FGF7(1)						SVEP1(1)							LAMB1(1)	SON(2)				NID1(1)	LAMC1(1)			EMILIN1(1)				STAT3(1)			LIMA1(1)		KLF9(2)		NFIB(1)									COL15A1(1)		LAMA2(1)							
Pancreas-nk(1) 																																																																																																						
Pancreas-plasma(1) 								TMEM258(1)														RABAC1(1)																																																																																
Fat-endothelial(1) 																																																																																																						
Fat-fibroblast(1)																																																																																																						
Fat-leucocyte(1)																																																																																																							
Fat-macrophage(1)																																																																																																						
Fat-mast(1) 																																																																																																			
Fat-mesenchymal(1)  																																																																																																						
Fat-myofibroblast(1) 																																																																																																						
Fat-neutrophil(1)																										NABP1(1)																IRS2(1)														PTPRE(1)																																						RESF1(3)								
Fat-nk(1) 																																																																																																						
Fat-plasma(1) 																																																																																																						
Fat-smooth(1)  																																																																																																PLN(1)					
Fat-t(1) 																																																																																																						
Skin-cd141-positive(1)   														IDO1(2)										NFKB1(1)																			DAPP1(1)													PMAIP1(2)								CCL22(3)										REL(3)							CXCL5(3)			CCR7(2)																	MAP4K4(2)	
Skin-cd1c-positive(1)   																																																																		MRPS6(1)																																				
Skin-cd4-positive(2)   																																																																																																						
,    																																																																																																						
Skin-cd8-positive(2),  Cytotoxic(2)  																																																																																																						
,    																																																																																																						
Skin-endothelial(1) 																																																																											MMP1(2)																											
Skin-epithelial(1) 																										MUCL1(1)																																					SCGB1D2(1)																				SDC4(1)					DCD(1)					SCGB2A2(2)									
Skin-langerhans(1) 													RALA(1)												MTHFR(1)																																				DUSP5(2)						MTSS1(1)												STK4(1)		PGK1(1)		CYTIP(1)		HLA-DQA2(1)															GPAT3(1)		
Skin-macrophage(1)																																																																																																					
Skin-mast(1) 																																																																																			SOCS1(1)																			
Skin-melanocyte(1)																																																																																																						
Skin-memory(1)  																																																																																																					
Skin-muscle(1) 																																																																																																						
Skin-naive(3)  																												ARID5B(1)																																																																										
  ,   																																																																																																						
  ,   																																																																																																						
Skin-nk(1) 																																																																																																						
Skin-nkt(1) 																																																																																																						
Skin-plasma(1) 																																																																																																						
Skin-regulatory(1)  								BATF(1)												UGP2(1)																																																																																		
Skin-stromal(1) 																																																																																								AKR1C1(1)														
Skin-t(1) 																																																																																																						
 Marrow-nampt(1) 																																																													BCL6(2)																																									
Heart-cardiac(2)  																																																																																																						
  									MYL7(2)		MYL4(2)																						TNNT2(2)																												NPPB(1)																MYH6(1)				SLC25A3(1)									COX6B1(1)												
Heart-fibroblast(1)  Cardiac(1) 																																																																														CRLF1(1)																								
Heart-hepatocyte(1)																																																																																																						
Heart-macrophage(1)																																																																																																						
Heart-smooth(1)  																																																																																																						
 Marrow-erythrocyte(1)																				SPECC1(1)				ANK1(1)			MOB1B(1)		TFDP2(1)				RSRP1(1)																SOX6(1)																		FAXDC2(1)															USP15(1)	ZNF451(1)				RB1CC1(1)						HECTD4(1)	FGFR1OP2(1)								
 Marrow-neutrophil(1)																																																															RTN3(1)					LRRK2(1)																																		
 Intestine-cd4-positive(2),   																																																																																																						
 Intestine-enterocyte(2)     																																																																																																						
       		HEXIM1(1)																						SLC38A2(1)																																																																														
   											EHF(1)				AVIL(1)			CCND1(1)									IL17RB(1)																										RASSF6(1)																	POU2F3(1)	BMX(1)																	MAP7(1)													
 Intestine-large(1)   																																																																																		ST6GALNAC1(1)																		FAM3D(1)		
 Intestine-mast(2) 																																																																																																						
 Intestine-monocyte(2)		WSB1(1)						SRSF3(1)													SCN7A(2)											MAFF(2)	RCAN1(2)																																			IRF1(2)				CYCS(2)					NRXN1(2)						LGI4(2)					TCIM(3)										SAMHD1(1)		SERTAD1(1)		
 Intestine-neutrophil(2)									ATP1B3(1)																																																																																													
 Intestine-plasma(2) 																																																																																																						
 																																																																																																						
Liver-erythrocyte(1)																																																																																																						
   																																																																															PDLIM1(1)																							
   																																																																																																						
   																																																																																																						
 Mucous(1) 																																																																																																					
Lung-smooth(1)  																																																																																																						
Muscle-mesothelial(1) 																																																																																																						
Muscle-smooth(1)  																																																				RERGL(1)																																																		
Prostate-club(1)    																																																																				TGM4(1)																																		
Prostate-hillock(1)    																																																																																																						
Prostate-mast(1) 																																																																																																						
Prostate-myeloid(1) 																																																																																																						
Prostate-neutrophil(1)		IFRD1(1)																																																																																																				
Prostate-sperm(1)																																																			FAM107B(1)																																																			
Prostate-t(1) 																																																																																																						
 Gland-ionocyte(1)																																			TMPRSS11E(1)																																	MUC16(1)													TFCP2L1(1)						KTN1(1)														
 Gland-macrophage(1)																																																																																																						
 Gland-salivary(1)  																																																																																																						
Skin-cell(1)  Skeletal(1) 																																																																																																						
Skin-smooth(1)  																																																																																																						
 ,   																																																																																																						
      																																																																																																						
       																																																																					CCL25(1)																		HBEGF(1)															
  																																																																																																						
 																												ANK3(1)																																																																										
 																																																																																																						
  																																																																																																						
 Intestine-small(1)   		SPINK4(1)																	RRBP1(1)																																																																																			
Thymus-b(1) 																																																																																																						
,    																																																																																																						
Thymus-dn1(1)  Pro-T(1) 																																																																																																						
Thymus-dn3(1) 																																																																																																						
Thymus-dn4(1) 																																																					CORO1A(1)																																																	
Thymus-innate(1)  																																																																																																						
Thymus-myeloid(1)  																																																																																																					
 Regulatory(1)  																																																																																																						
Thymus-t(1) Follicular(1)  																																																																																																						
Tongue-schwann(1) 																																																																																GAS7(1)																					
Vasculature-artery(1)  										CXCL12(1)																																																																RDX(1)																												
Vasculature-lymphatic(1)  																																																																																																						
Eye-adipocyte(1)											SOAT1(1)																FDPS(1)																																																	HMGCS1(1)				DHCR24(1)									GAL(1)								MSMO1(1)					
 Ganglion(1) 																	UQCR11(1)																										COX17(1)										ATP5MC2(1)																												NDUFB1(1)	"

```


```{r}
parse_one <- function(input_string) {
  genes <- unlist(strsplit(input_string, "[\t ]+"))  # Split string by tabs or spaces
  end_one <- grep("\\(1\\)$", genes, value = TRUE)  # Find words ending in (1)
  return(end_one)
}

# Test the function
input_string <- "apple(1) banana orange(1) cherry pear(2) grape(1)"
result <- parse_one(TabulaSapiens)

remove_parentheses_one <- function(genelist) {
  cleaned_items <- gsub("\\(1\\)$", "", genelist)
  return(cleaned_items)
}

# Test the function
cleaned_items <- remove_parentheses_one(result)
print(cleaned_items)
cat(cleaned_items, sep = " ")
```